puts "Seeding vocabularies..."

vocabularies = {
  rails: [
    { english: "scaffold", chinese: "鷹架（快速產生 CRUD）", difficulty: 1 },
    { english: "migration", chinese: "遷移（資料庫版本控制）", difficulty: 1 },
    { english: "routing", chinese: "路由", difficulty: 1 },
    { english: "controller", chinese: "控制器", difficulty: 1 },
    { english: "model", chinese: "模型", difficulty: 1 },
    { english: "view", chinese: "視圖", difficulty: 1 },
    { english: "partial", chinese: "局部樣板", difficulty: 2 },
    { english: "helper", chinese: "輔助方法", difficulty: 1 },
    { english: "concern", chinese: "關注點（模組化共用邏輯）", difficulty: 2 },
    { english: "callback", chinese: "回呼", difficulty: 2 },
    { english: "validation", chinese: "驗證", difficulty: 1 },
    { english: "association", chinese: "關聯", difficulty: 2 },
    { english: "scope", chinese: "範圍查詢", difficulty: 2 },
    { english: "turbo", chinese: "渦輪（Hotwire 頁面加速）", difficulty: 2 },
    { english: "stimulus", chinese: "刺激（Hotwire JS 框架）", difficulty: 2 },
    { english: "devise", chinese: "認證套件", difficulty: 2 },
    { english: "middleware", chinese: "中介軟體", difficulty: 2 },
    { english: "asset", chinese: "靜態資源", difficulty: 1 },
    { english: "deployment", chinese: "部署", difficulty: 1 },
    { english: "mailer", chinese: "郵件寄送器", difficulty: 2 },
    { english: "serializer", chinese: "序列化器", difficulty: 2 },
    { english: "initializer", chinese: "初始化設定檔", difficulty: 2 },
    { english: "generator", chinese: "產生器", difficulty: 1 },
    { english: "rake", chinese: "任務執行工具", difficulty: 2 },
    { english: "yield", chinese: "讓渡（輸出內容區塊）", difficulty: 3 },
  ],
  general: [
    { english: "implement", chinese: "實作", difficulty: 1 },
    { english: "deprecated", chinese: "已棄用的", difficulty: 2 },
    { english: "initialize", chinese: "初始化", difficulty: 1 },
    { english: "configure", chinese: "設定", difficulty: 1 },
    { english: "parameter", chinese: "參數", difficulty: 1 },
    { english: "instance", chinese: "實例", difficulty: 2 },
    { english: "variable", chinese: "變數", difficulty: 1 },
    { english: "method", chinese: "方法", difficulty: 1 },
    { english: "function", chinese: "函式", difficulty: 1 },
    { english: "argument", chinese: "引數", difficulty: 2 },
    { english: "syntax", chinese: "語法", difficulty: 1 },
    { english: "compile", chinese: "編譯", difficulty: 2 },
    { english: "execute", chinese: "執行", difficulty: 1 },
    { english: "debug", chinese: "除錯", difficulty: 1 },
    { english: "refactor", chinese: "重構", difficulty: 2 },
    { english: "iterate", chinese: "迭代", difficulty: 2 },
    { english: "deploy", chinese: "部署", difficulty: 1 },
    { english: "repository", chinese: "儲存庫", difficulty: 1 },
    { english: "dependency", chinese: "依賴", difficulty: 2 },
    { english: "environment", chinese: "環境", difficulty: 1 },
    { english: "inheritance", chinese: "繼承", difficulty: 2 },
    { english: "polymorphism", chinese: "多型", difficulty: 3 },
    { english: "encapsulation", chinese: "封裝", difficulty: 3 },
    { english: "abstraction", chinese: "抽象化", difficulty: 3 },
    { english: "convention", chinese: "慣例", difficulty: 2 },
  ],
  database: [
    { english: "schema", chinese: "結構描述", difficulty: 2 },
    { english: "query", chinese: "查詢", difficulty: 1 },
    { english: "index", chinese: "索引", difficulty: 2 },
    { english: "transaction", chinese: "交易", difficulty: 2 },
    { english: "constraint", chinese: "約束條件", difficulty: 2 },
    { english: "normalize", chinese: "正規化", difficulty: 3 },
    { english: "aggregate", chinese: "聚合", difficulty: 2 },
    { english: "join", chinese: "聯結", difficulty: 1 },
    { english: "primary key", chinese: "主鍵", difficulty: 1 },
    { english: "foreign key", chinese: "外鍵", difficulty: 1 },
    { english: "seed", chinese: "種子資料", difficulty: 1 },
    { english: "rollback", chinese: "回滾", difficulty: 2 },
    { english: "column", chinese: "欄位", difficulty: 1 },
    { english: "table", chinese: "資料表", difficulty: 1 },
    { english: "record", chinese: "記錄", difficulty: 1 },
    { english: "relation", chinese: "關聯", difficulty: 2 },
    { english: "persistence", chinese: "持久化", difficulty: 3 },
    { english: "throughput", chinese: "吞吐量", difficulty: 3 },
    { english: "replication", chinese: "複製（資料庫同步）", difficulty: 3 },
    { english: "partition", chinese: "分區", difficulty: 3 },
    { english: "deadlock", chinese: "死鎖", difficulty: 3 },
    { english: "cursor", chinese: "游標", difficulty: 2 },
  ],
  frontend: [
    { english: "component", chinese: "元件", difficulty: 1 },
    { english: "render", chinese: "渲染", difficulty: 1 },
    { english: "responsive", chinese: "響應式的", difficulty: 1 },
    { english: "layout", chinese: "版面配置", difficulty: 1 },
    { english: "stylesheet", chinese: "樣式表", difficulty: 1 },
    { english: "viewport", chinese: "視窗", difficulty: 2 },
    { english: "accessibility", chinese: "無障礙性", difficulty: 2 },
    { english: "animation", chinese: "動畫", difficulty: 1 },
    { english: "framework", chinese: "框架", difficulty: 1 },
    { english: "DOM", chinese: "文件物件模型", difficulty: 2 },
    { english: "event", chinese: "事件", difficulty: 1 },
    { english: "listener", chinese: "監聽器", difficulty: 2 },
    { english: "selector", chinese: "選擇器", difficulty: 2 },
    { english: "template", chinese: "模板", difficulty: 1 },
    { english: "binding", chinese: "綁定", difficulty: 2 },
    { english: "reactive", chinese: "響應式的（資料驅動）", difficulty: 2 },
    { english: "hydration", chinese: "水合（伺服器渲染後啟動）", difficulty: 3 },
    { english: "bundle", chinese: "打包", difficulty: 2 },
    { english: "minify", chinese: "壓縮（程式碼）", difficulty: 2 },
    { english: "transpile", chinese: "轉譯", difficulty: 3 },
    { english: "flexbox", chinese: "彈性盒子佈局", difficulty: 2 },
    { english: "grid", chinese: "網格佈局", difficulty: 1 },
  ],
  backend: [
    { english: "endpoint", chinese: "端點", difficulty: 1 },
    { english: "authentication", chinese: "身份驗證", difficulty: 1 },
    { english: "authorization", chinese: "授權", difficulty: 2 },
    { english: "session", chinese: "會話", difficulty: 1 },
    { english: "token", chinese: "令牌", difficulty: 2 },
    { english: "cache", chinese: "快取", difficulty: 1 },
    { english: "queue", chinese: "佇列", difficulty: 2 },
    { english: "webhook", chinese: "網路鉤子", difficulty: 2 },
    { english: "API", chinese: "應用程式介面", difficulty: 1 },
    { english: "request", chinese: "請求", difficulty: 1 },
    { english: "response", chinese: "回應", difficulty: 1 },
    { english: "header", chinese: "標頭", difficulty: 2 },
    { english: "payload", chinese: "酬載（請求內容）", difficulty: 2 },
    { english: "encryption", chinese: "加密", difficulty: 2 },
    { english: "hashing", chinese: "雜湊", difficulty: 2 },
    { english: "latency", chinese: "延遲", difficulty: 2 },
    { english: "microservice", chinese: "微服務", difficulty: 2 },
    { english: "rate limiting", chinese: "速率限制", difficulty: 2 },
    { english: "idempotent", chinese: "冪等的", difficulty: 3 },
    { english: "pagination", chinese: "分頁", difficulty: 1 },
    { english: "throttle", chinese: "節流", difficulty: 3 },
    { english: "socket", chinese: "通訊端口", difficulty: 2 },
  ],
  devops: [
    { english: "container", chinese: "容器", difficulty: 1 },
    { english: "orchestration", chinese: "編排", difficulty: 3 },
    { english: "pipeline", chinese: "管線（CI/CD 流程）", difficulty: 2 },
    { english: "monitoring", chinese: "監控", difficulty: 1 },
    { english: "scaling", chinese: "擴展", difficulty: 2 },
    { english: "load balancer", chinese: "負載均衡器", difficulty: 2 },
    { english: "registry", chinese: "映像檔倉庫", difficulty: 2 },
    { english: "volume", chinese: "卷（資料儲存）", difficulty: 2 },
    { english: "cluster", chinese: "叢集", difficulty: 2 },
    { english: "namespace", chinese: "命名空間", difficulty: 2 },
    { english: "ingress", chinese: "入口（流量管理）", difficulty: 3 },
    { english: "rollout", chinese: "滾動更新", difficulty: 2 },
    { english: "artifact", chinese: "產出物", difficulty: 2 },
    { english: "provisioning", chinese: "資源配置", difficulty: 3 },
    { english: "infrastructure", chinese: "基礎設施", difficulty: 2 },
    { english: "logging", chinese: "日誌記錄", difficulty: 1 },
    { english: "alerting", chinese: "告警", difficulty: 1 },
    { english: "uptime", chinese: "正常運行時間", difficulty: 1 },
    { english: "failover", chinese: "故障轉移", difficulty: 3 },
    { english: "CI/CD", chinese: "持續整合/持續部署", difficulty: 1 },
    { english: "Docker", chinese: "容器化平台", difficulty: 1 },
    { english: "Kubernetes", chinese: "容器編排平台", difficulty: 2 },
    { english: "daemon", chinese: "守護程序", difficulty: 2 },
    { english: "cron job", chinese: "排程任務", difficulty: 2 },
    { english: "health check", chinese: "健康檢查", difficulty: 1 },
    { english: "environment variable", chinese: "環境變數", difficulty: 1 },
    { english: "image", chinese: "映像檔", difficulty: 1 },
    { english: "tag", chinese: "標籤（版本標記）", difficulty: 1 },
    { english: "service", chinese: "服務", difficulty: 1 },
    { english: "proxy", chinese: "代理伺服器", difficulty: 2 },
    { english: "reverse proxy", chinese: "反向代理", difficulty: 2 },
    { english: "downtime", chinese: "停機時間", difficulty: 1 },
    { english: "blue-green deployment", chinese: "藍綠部署", difficulty: 2 },
    { english: "canary deployment", chinese: "金絲雀部署", difficulty: 2 },
    { english: "horizontal scaling", chinese: "水平擴展", difficulty: 2 },
    { english: "vertical scaling", chinese: "垂直擴展", difficulty: 2 },
  ],
  general_2: [
    { english: "boolean", chinese: "布林值", difficulty: 1 },
    { english: "string", chinese: "字串", difficulty: 1 },
    { english: "integer", chinese: "整數", difficulty: 1 },
    { english: "float", chinese: "浮點數", difficulty: 1 },
    { english: "array", chinese: "陣列", difficulty: 1 },
    { english: "hash", chinese: "雜湊（鍵值對集合）", difficulty: 1 },
    { english: "object", chinese: "物件", difficulty: 1 },
    { english: "class", chinese: "類別", difficulty: 1 },
    { english: "module", chinese: "模組", difficulty: 1 },
    { english: "interface", chinese: "介面", difficulty: 2 },
    { english: "library", chinese: "函式庫", difficulty: 1 },
    { english: "package", chinese: "套件", difficulty: 1 },
    { english: "constant", chinese: "常數", difficulty: 1 },
    { english: "attribute", chinese: "屬性", difficulty: 1 },
    { english: "property", chinese: "屬性（物件的）", difficulty: 1 },
    { english: "return value", chinese: "回傳值", difficulty: 1 },
    { english: "exception", chinese: "例外", difficulty: 2 },
    { english: "error handling", chinese: "錯誤處理", difficulty: 1 },
    { english: "stack trace", chinese: "堆疊追蹤", difficulty: 2 },
    { english: "runtime", chinese: "執行環境", difficulty: 2 },
    { english: "loop", chinese: "迴圈", difficulty: 1 },
    { english: "condition", chinese: "條件", difficulty: 1 },
    { english: "operator", chinese: "運算子", difficulty: 1 },
    { english: "expression", chinese: "表達式", difficulty: 2 },
    { english: "statement", chinese: "陳述句", difficulty: 2 },
    { english: "block", chinese: "區塊", difficulty: 1 },
    { english: "closure", chinese: "閉包", difficulty: 2 },
    { english: "lambda", chinese: "匿名函式", difficulty: 2 },
    { english: "recursion", chinese: "遞迴", difficulty: 2 },
    { english: "algorithm", chinese: "演算法", difficulty: 1 },
    { english: "data structure", chinese: "資料結構", difficulty: 1 },
    { english: "type", chinese: "型別", difficulty: 1 },
    { english: "cast", chinese: "型別轉換", difficulty: 2 },
    { english: "parse", chinese: "解析", difficulty: 1 },
    { english: "format", chinese: "格式化", difficulty: 1 },
    { english: "encode", chinese: "編碼", difficulty: 1 },
    { english: "decode", chinese: "解碼", difficulty: 1 },
    { english: "serialize", chinese: "序列化", difficulty: 2 },
    { english: "deserialize", chinese: "反序列化", difficulty: 2 },
    { english: "immutable", chinese: "不可變的", difficulty: 2 },
    { english: "mutable", chinese: "可變的", difficulty: 2 },
    { english: "thread", chinese: "執行緒", difficulty: 2 },
    { english: "process", chinese: "程序", difficulty: 1 },
    { english: "concurrent", chinese: "並發的", difficulty: 2 },
    { english: "asynchronous", chinese: "非同步的", difficulty: 2 },
    { english: "synchronous", chinese: "同步的", difficulty: 2 },
    { english: "callback", chinese: "回呼函式", difficulty: 2 },
    { english: "promise", chinese: "承諾（非同步處理）", difficulty: 2 },
    { english: "enum", chinese: "列舉", difficulty: 2 },
    { english: "tuple", chinese: "元組", difficulty: 2 },
    { english: "literal", chinese: "字面值", difficulty: 2 },
    { english: "annotation", chinese: "註解", difficulty: 2 },
    { english: "decorator", chinese: "裝飾器", difficulty: 2 },
    { english: "pattern", chinese: "模式", difficulty: 1 },
    { english: "design pattern", chinese: "設計模式", difficulty: 2 },
    { english: "singleton", chinese: "單例模式", difficulty: 2 },
    { english: "factory", chinese: "工廠模式", difficulty: 2 },
    { english: "observer", chinese: "觀察者模式", difficulty: 2 },
    { english: "verbose", chinese: "詳細的（輸出）", difficulty: 2 },
    { english: "truncate", chinese: "截斷", difficulty: 2 },
    { english: "compatible", chinese: "相容的", difficulty: 1 },
    { english: "backward compatible", chinese: "向下相容的", difficulty: 2 },
    { english: "breaking change", chinese: "破壞性變更", difficulty: 2 },
    { english: "workaround", chinese: "替代方案", difficulty: 1 },
    { english: "boilerplate", chinese: "樣板程式碼", difficulty: 2 },
    { english: "snippet", chinese: "程式碼片段", difficulty: 1 },
    { english: "flag", chinese: "旗標（選項開關）", difficulty: 1 },
    { english: "toggle", chinese: "切換", difficulty: 1 },
    { english: "default", chinese: "預設值", difficulty: 1 },
    { english: "override", chinese: "覆寫", difficulty: 2 },
    { english: "fallback", chinese: "備援方案", difficulty: 2 },
    { english: "graceful", chinese: "優雅的（如優雅關閉）", difficulty: 2 },
  ],
  database_2: [
    { english: "migration", chinese: "資料庫遷移", difficulty: 1 },
    { english: "insert", chinese: "新增資料", difficulty: 1 },
    { english: "update", chinese: "更新資料", difficulty: 1 },
    { english: "delete", chinese: "刪除資料", difficulty: 1 },
    { english: "select", chinese: "查詢資料", difficulty: 1 },
    { english: "where clause", chinese: "條件子句", difficulty: 1 },
    { english: "order by", chinese: "排序", difficulty: 1 },
    { english: "group by", chinese: "分組", difficulty: 2 },
    { english: "having", chinese: "分組後篩選", difficulty: 2 },
    { english: "subquery", chinese: "子查詢", difficulty: 2 },
    { english: "left join", chinese: "左聯結", difficulty: 2 },
    { english: "inner join", chinese: "內聯結", difficulty: 2 },
    { english: "unique index", chinese: "唯一索引", difficulty: 2 },
    { english: "composite index", chinese: "複合索引", difficulty: 2 },
    { english: "CRUD", chinese: "新增讀取更新刪除", difficulty: 1 },
    { english: "ORM", chinese: "物件關聯映射", difficulty: 2 },
    { english: "N+1 query", chinese: "N+1 查詢問題", difficulty: 2 },
    { english: "eager loading", chinese: "預先載入", difficulty: 2 },
    { english: "lazy loading", chinese: "延遲載入", difficulty: 2 },
    { english: "connection pool", chinese: "連線池", difficulty: 2 },
    { english: "backup", chinese: "備份", difficulty: 1 },
    { english: "restore", chinese: "還原", difficulty: 1 },
    { english: "dump", chinese: "傾印（匯出資料）", difficulty: 2 },
    { english: "trigger", chinese: "觸發器", difficulty: 2 },
    { english: "stored procedure", chinese: "預存程序", difficulty: 2 },
    { english: "view", chinese: "檢視表", difficulty: 2 },
    { english: "null", chinese: "空值", difficulty: 1 },
    { english: "default value", chinese: "預設值", difficulty: 1 },
    { english: "data type", chinese: "資料型別", difficulty: 1 },
    { english: "charset", chinese: "字元集", difficulty: 2 },
  ],
  frontend_2: [
    { english: "CSS", chinese: "階層式樣式表", difficulty: 1 },
    { english: "HTML", chinese: "超文本標記語言", difficulty: 1 },
    { english: "JavaScript", chinese: "前端程式語言", difficulty: 1 },
    { english: "hover", chinese: "滑鼠懸停", difficulty: 1 },
    { english: "click event", chinese: "點擊事件", difficulty: 1 },
    { english: "submit", chinese: "提交", difficulty: 1 },
    { english: "form", chinese: "表單", difficulty: 1 },
    { english: "input", chinese: "輸入欄位", difficulty: 1 },
    { english: "button", chinese: "按鈕", difficulty: 1 },
    { english: "dropdown", chinese: "下拉選單", difficulty: 1 },
    { english: "modal", chinese: "彈出視窗", difficulty: 1 },
    { english: "tooltip", chinese: "提示框", difficulty: 1 },
    { english: "breadcrumb", chinese: "麵包屑導覽", difficulty: 2 },
    { english: "carousel", chinese: "輪播", difficulty: 2 },
    { english: "pagination", chinese: "分頁元件", difficulty: 1 },
    { english: "lazy load", chinese: "延遲載入（圖片）", difficulty: 2 },
    { english: "placeholder", chinese: "預留位置文字", difficulty: 1 },
    { english: "margin", chinese: "外邊距", difficulty: 1 },
    { english: "padding", chinese: "內邊距", difficulty: 1 },
    { english: "border", chinese: "邊框", difficulty: 1 },
    { english: "overflow", chinese: "溢出", difficulty: 2 },
    { english: "z-index", chinese: "堆疊層級", difficulty: 2 },
    { english: "opacity", chinese: "透明度", difficulty: 1 },
    { english: "transition", chinese: "過渡效果", difficulty: 2 },
    { english: "media query", chinese: "媒體查詢（RWD）", difficulty: 2 },
    { english: "breakpoint", chinese: "斷點（RWD 寬度）", difficulty: 2 },
    { english: "font", chinese: "字型", difficulty: 1 },
    { english: "icon", chinese: "圖示", difficulty: 1 },
    { english: "SVG", chinese: "可縮放向量圖形", difficulty: 2 },
    { english: "pixel", chinese: "像素", difficulty: 1 },
  ],
  backend_2: [
    { english: "REST", chinese: "表現層狀態轉移", difficulty: 2 },
    { english: "GraphQL", chinese: "圖形查詢語言", difficulty: 2 },
    { english: "JSON", chinese: "JavaScript 物件表示法", difficulty: 1 },
    { english: "XML", chinese: "可延伸標記語言", difficulty: 2 },
    { english: "CORS", chinese: "跨來源資源共享", difficulty: 2 },
    { english: "CSRF", chinese: "跨站請求偽造", difficulty: 2 },
    { english: "XSS", chinese: "跨站腳本攻擊", difficulty: 2 },
    { english: "status code", chinese: "狀態碼", difficulty: 1 },
    { english: "redirect", chinese: "重新導向", difficulty: 1 },
    { english: "cookie", chinese: "瀏覽器小型文字檔", difficulty: 1 },
    { english: "middleware", chinese: "中介軟體", difficulty: 2 },
    { english: "route", chinese: "路由", difficulty: 1 },
    { english: "controller", chinese: "控制器", difficulty: 1 },
    { english: "service object", chinese: "服務物件", difficulty: 2 },
    { english: "background job", chinese: "背景任務", difficulty: 2 },
    { english: "worker", chinese: "工作者程序", difficulty: 2 },
    { english: "cron", chinese: "排程", difficulty: 2 },
    { english: "timeout", chinese: "逾時", difficulty: 1 },
    { english: "retry", chinese: "重試", difficulty: 1 },
    { english: "rate limit", chinese: "速率限制", difficulty: 2 },
    { english: "upload", chinese: "上傳", difficulty: 1 },
    { english: "download", chinese: "下載", difficulty: 1 },
    { english: "stream", chinese: "串流", difficulty: 2 },
    { english: "batch", chinese: "批次處理", difficulty: 2 },
    { english: "log level", chinese: "日誌等級", difficulty: 2 },
    { english: "debug mode", chinese: "除錯模式", difficulty: 1 },
    { english: "production", chinese: "正式環境", difficulty: 1 },
    { english: "staging", chinese: "預備環境", difficulty: 2 },
    { english: "development", chinese: "開發環境", difficulty: 1 },
    { english: "sandbox", chinese: "沙箱環境", difficulty: 2 },
  ],
  network: [
    { english: "HTTP", chinese: "超文本傳輸協定", difficulty: 1 },
    { english: "HTTPS", chinese: "安全超文本傳輸協定", difficulty: 1 },
    { english: "TCP", chinese: "傳輸控制協定", difficulty: 2 },
    { english: "UDP", chinese: "使用者資料報協定", difficulty: 2 },
    { english: "IP address", chinese: "網際協定位址", difficulty: 1 },
    { english: "DNS", chinese: "網域名稱系統", difficulty: 1 },
    { english: "domain", chinese: "網域", difficulty: 1 },
    { english: "subdomain", chinese: "子網域", difficulty: 1 },
    { english: "port", chinese: "連接埠", difficulty: 1 },
    { english: "protocol", chinese: "協定", difficulty: 1 },
    { english: "SSL", chinese: "安全通訊協定", difficulty: 2 },
    { english: "TLS", chinese: "傳輸層安全協定", difficulty: 2 },
    { english: "certificate", chinese: "憑證", difficulty: 2 },
    { english: "firewall", chinese: "防火牆", difficulty: 1 },
    { english: "bandwidth", chinese: "頻寬", difficulty: 2 },
    { english: "CDN", chinese: "內容傳遞網路", difficulty: 2 },
    { english: "WebSocket", chinese: "網路通訊端口", difficulty: 2 },
    { english: "handshake", chinese: "交握（連線建立）", difficulty: 2 },
    { english: "ping", chinese: "偵測連線", difficulty: 1 },
    { english: "URL", chinese: "統一資源定位符", difficulty: 1 },
    { english: "URI", chinese: "統一資源識別符", difficulty: 2 },
    { english: "query string", chinese: "查詢字串", difficulty: 1 },
    { english: "path", chinese: "路徑", difficulty: 1 },
    { english: "host", chinese: "主機", difficulty: 1 },
    { english: "server", chinese: "伺服器", difficulty: 1 },
    { english: "client", chinese: "客戶端", difficulty: 1 },
    { english: "gateway", chinese: "閘道", difficulty: 2 },
    { english: "VPN", chinese: "虛擬私人網路", difficulty: 1 },
    { english: "SSH", chinese: "安全殼層協定", difficulty: 2 },
    { english: "FTP", chinese: "檔案傳輸協定", difficulty: 1 },
  ],
  testing: [
    { english: "unit test", chinese: "單元測試", difficulty: 1 },
    { english: "integration test", chinese: "整合測試", difficulty: 2 },
    { english: "system test", chinese: "系統測試", difficulty: 2 },
    { english: "end-to-end test", chinese: "端對端測試", difficulty: 2 },
    { english: "test case", chinese: "測試案例", difficulty: 1 },
    { english: "test suite", chinese: "測試套件", difficulty: 1 },
    { english: "assertion", chinese: "斷言", difficulty: 2 },
    { english: "expect", chinese: "預期", difficulty: 1 },
    { english: "mock", chinese: "模擬物件", difficulty: 2 },
    { english: "stub", chinese: "替身物件", difficulty: 2 },
    { english: "fixture", chinese: "測試固定資料", difficulty: 2 },
    { english: "factory", chinese: "測試資料工廠", difficulty: 2 },
    { english: "coverage", chinese: "測試覆蓋率", difficulty: 1 },
    { english: "regression", chinese: "回歸測試", difficulty: 2 },
    { english: "TDD", chinese: "測試驅動開發", difficulty: 2 },
    { english: "BDD", chinese: "行為驅動開發", difficulty: 2 },
    { english: "spec", chinese: "規格（測試描述）", difficulty: 1 },
    { english: "describe", chinese: "描述（測試區塊）", difficulty: 1 },
    { english: "context", chinese: "情境（測試區塊）", difficulty: 1 },
    { english: "before hook", chinese: "前置鉤子", difficulty: 2 },
    { english: "after hook", chinese: "後置鉤子", difficulty: 2 },
    { english: "pending", chinese: "待完成的測試", difficulty: 1 },
    { english: "pass", chinese: "通過", difficulty: 1 },
    { english: "fail", chinese: "失敗", difficulty: 1 },
    { english: "flaky test", chinese: "不穩定的測試", difficulty: 2 },
  ],
  git: [
    { english: "commit", chinese: "提交", difficulty: 1 },
    { english: "branch", chinese: "分支", difficulty: 1 },
    { english: "merge", chinese: "合併", difficulty: 1 },
    { english: "rebase", chinese: "變基（重新定位基準）", difficulty: 2 },
    { english: "pull request", chinese: "合併請求", difficulty: 1 },
    { english: "push", chinese: "推送", difficulty: 1 },
    { english: "pull", chinese: "拉取", difficulty: 1 },
    { english: "fetch", chinese: "擷取（遠端資料）", difficulty: 1 },
    { english: "clone", chinese: "克隆（複製儲存庫）", difficulty: 1 },
    { english: "fork", chinese: "分叉（複製他人專案）", difficulty: 1 },
    { english: "conflict", chinese: "衝突", difficulty: 1 },
    { english: "resolve", chinese: "解決（衝突）", difficulty: 1 },
    { english: "staging area", chinese: "暫存區", difficulty: 2 },
    { english: "diff", chinese: "差異比較", difficulty: 1 },
    { english: "stash", chinese: "暫存變更", difficulty: 2 },
    { english: "checkout", chinese: "切換分支", difficulty: 1 },
    { english: "reset", chinese: "重置", difficulty: 2 },
    { english: "revert", chinese: "還原提交", difficulty: 2 },
    { english: "cherry-pick", chinese: "揀選提交", difficulty: 2 },
    { english: "remote", chinese: "遠端儲存庫", difficulty: 1 },
    { english: "origin", chinese: "預設遠端名稱", difficulty: 1 },
    { english: "main branch", chinese: "主分支", difficulty: 1 },
    { english: "feature branch", chinese: "功能分支", difficulty: 1 },
    { english: "hotfix", chinese: "緊急修復", difficulty: 1 },
    { english: "release", chinese: "發布版本", difficulty: 1 },
    { english: "changelog", chinese: "變更日誌", difficulty: 1 },
    { english: "version control", chinese: "版本控制", difficulty: 1 },
    { english: "gitignore", chinese: "Git 忽略清單", difficulty: 1 },
  ],
  cloud: [
    { english: "cloud computing", chinese: "雲端運算", difficulty: 1 },
    { english: "SaaS", chinese: "軟體即服務", difficulty: 2 },
    { english: "PaaS", chinese: "平台即服務", difficulty: 2 },
    { english: "IaaS", chinese: "基礎設施即服務", difficulty: 2 },
    { english: "serverless", chinese: "無伺服器架構", difficulty: 2 },
    { english: "Lambda", chinese: "無伺服器函式（AWS）", difficulty: 2 },
    { english: "S3", chinese: "簡易儲存服務（AWS）", difficulty: 1 },
    { english: "EC2", chinese: "彈性運算雲端（AWS）", difficulty: 2 },
    { english: "region", chinese: "區域（資料中心位置）", difficulty: 1 },
    { english: "availability zone", chinese: "可用區域", difficulty: 2 },
    { english: "auto scaling", chinese: "自動擴展", difficulty: 2 },
    { english: "instance", chinese: "實例（雲端主機）", difficulty: 1 },
    { english: "bucket", chinese: "儲存桶", difficulty: 1 },
    { english: "object storage", chinese: "物件儲存", difficulty: 2 },
    { english: "blob", chinese: "二進位大型物件", difficulty: 2 },
    { english: "cloud function", chinese: "雲端函式", difficulty: 1 },
    { english: "managed service", chinese: "託管服務", difficulty: 2 },
    { english: "tenant", chinese: "租戶", difficulty: 2 },
    { english: "multi-tenant", chinese: "多租戶架構", difficulty: 2 },
    { english: "on-premise", chinese: "本地部署", difficulty: 2 },
    { english: "hybrid cloud", chinese: "混合雲", difficulty: 2 },
    { english: "quota", chinese: "配額", difficulty: 1 },
    { english: "billing", chinese: "計費", difficulty: 1 },
    { english: "IAM", chinese: "身份存取管理", difficulty: 2 },
    { english: "policy", chinese: "政策（權限規則）", difficulty: 2 },
    { english: "resource", chinese: "資源", difficulty: 1 },
    { english: "provision", chinese: "配置資源", difficulty: 2 },
    { english: "terraform", chinese: "基礎設施即程式碼工具", difficulty: 2 },
    { english: "infrastructure as code", chinese: "基礎設施即程式碼", difficulty: 2 },
    { english: "stack", chinese: "堆疊（技術組合）", difficulty: 1 },
    { english: "cold start", chinese: "冷啟動", difficulty: 2 },
    { english: "warm start", chinese: "暖啟動", difficulty: 2 },
    { english: "edge computing", chinese: "邊緣運算", difficulty: 2 },
    { english: "content delivery", chinese: "內容傳遞", difficulty: 1 },
    { english: "elastic", chinese: "彈性的", difficulty: 1 },
    { english: "high availability", chinese: "高可用性", difficulty: 2 },
    { english: "disaster recovery", chinese: "災難復原", difficulty: 2 },
    { english: "SLA", chinese: "服務等級協議", difficulty: 2 },
    { english: "throughput", chinese: "吞吐量（雲端）", difficulty: 2 },
    { english: "egress", chinese: "出站流量", difficulty: 2 },
  ],
  agile: [
    { english: "agile", chinese: "敏捷開發", difficulty: 1 },
    { english: "scrum", chinese: "Scrum 框架", difficulty: 1 },
    { english: "sprint", chinese: "衝刺（迭代週期）", difficulty: 1 },
    { english: "backlog", chinese: "待辦清單", difficulty: 1 },
    { english: "user story", chinese: "使用者故事", difficulty: 1 },
    { english: "acceptance criteria", chinese: "驗收條件", difficulty: 2 },
    { english: "standup", chinese: "站立會議", difficulty: 1 },
    { english: "retrospective", chinese: "回顧會議", difficulty: 2 },
    { english: "velocity", chinese: "開發速度", difficulty: 2 },
    { english: "story point", chinese: "故事點數", difficulty: 2 },
    { english: "epic", chinese: "史詩（大型功能）", difficulty: 2 },
    { english: "kanban", chinese: "看板", difficulty: 1 },
    { english: "blocker", chinese: "阻礙因素", difficulty: 1 },
    { english: "stakeholder", chinese: "利害關係人", difficulty: 2 },
    { english: "deliverable", chinese: "交付項目", difficulty: 2 },
    { english: "milestone", chinese: "里程碑", difficulty: 1 },
    { english: "deadline", chinese: "截止日期", difficulty: 1 },
    { english: "priority", chinese: "優先順序", difficulty: 1 },
    { english: "estimate", chinese: "估算", difficulty: 1 },
    { english: "scope", chinese: "範圍（專案）", difficulty: 1 },
    { english: "scope creep", chinese: "範圍蔓延", difficulty: 2 },
    { english: "MVP", chinese: "最小可行產品", difficulty: 1 },
    { english: "iteration", chinese: "迭代", difficulty: 1 },
    { english: "increment", chinese: "增量", difficulty: 2 },
    { english: "burn down chart", chinese: "燃盡圖", difficulty: 2 },
    { english: "definition of done", chinese: "完成定義", difficulty: 2 },
    { english: "product owner", chinese: "產品負責人", difficulty: 1 },
    { english: "scrum master", chinese: "Scrum 主持人", difficulty: 1 },
    { english: "sprint review", chinese: "衝刺檢視會議", difficulty: 2 },
    { english: "daily standup", chinese: "每日站會", difficulty: 1 },
    { english: "roadmap", chinese: "產品路線圖", difficulty: 1 },
    { english: "release cycle", chinese: "發布週期", difficulty: 2 },
    { english: "continuous improvement", chinese: "持續改進", difficulty: 2 },
    { english: "lean", chinese: "精實方法", difficulty: 2 },
    { english: "technical debt", chinese: "技術債", difficulty: 1 },
    { english: "code review", chinese: "程式碼審查", difficulty: 1 },
    { english: "pair programming", chinese: "結對程式設計", difficulty: 2 },
    { english: "mob programming", chinese: "群體程式設計", difficulty: 2 },
  ],
  linux: [
    { english: "terminal", chinese: "終端機", difficulty: 1 },
    { english: "shell", chinese: "殼層（命令解譯器）", difficulty: 1 },
    { english: "bash", chinese: "Bourne Again Shell", difficulty: 1 },
    { english: "command line", chinese: "命令列", difficulty: 1 },
    { english: "root", chinese: "根目錄 / 最高權限", difficulty: 1 },
    { english: "sudo", chinese: "以管理員執行", difficulty: 1 },
    { english: "chmod", chinese: "變更檔案權限", difficulty: 2 },
    { english: "chown", chinese: "變更檔案擁有者", difficulty: 2 },
    { english: "directory", chinese: "目錄", difficulty: 1 },
    { english: "file system", chinese: "檔案系統", difficulty: 1 },
    { english: "symlink", chinese: "符號連結", difficulty: 2 },
    { english: "pipe", chinese: "管線（指令串接）", difficulty: 2 },
    { english: "redirect", chinese: "重導向（輸出）", difficulty: 2 },
    { english: "grep", chinese: "文字搜尋指令", difficulty: 1 },
    { english: "sed", chinese: "串流編輯器", difficulty: 2 },
    { english: "awk", chinese: "文字處理工具", difficulty: 2 },
    { english: "curl", chinese: "傳輸資料工具", difficulty: 1 },
    { english: "wget", chinese: "下載檔案工具", difficulty: 1 },
    { english: "tar", chinese: "打包壓縮工具", difficulty: 1 },
    { english: "package manager", chinese: "套件管理器", difficulty: 1 },
    { english: "apt", chinese: "Debian 套件管理", difficulty: 2 },
    { english: "yum", chinese: "Red Hat 套件管理", difficulty: 2 },
    { english: "systemd", chinese: "系統服務管理", difficulty: 2 },
    { english: "kernel", chinese: "核心", difficulty: 2 },
    { english: "distribution", chinese: "發行版", difficulty: 1 },
    { english: "stdout", chinese: "標準輸出", difficulty: 2 },
    { english: "stderr", chinese: "標準錯誤輸出", difficulty: 2 },
    { english: "stdin", chinese: "標準輸入", difficulty: 2 },
    { english: "exit code", chinese: "結束代碼", difficulty: 2 },
    { english: "PATH", chinese: "系統路徑變數", difficulty: 1 },
    { english: "alias", chinese: "指令別名", difficulty: 1 },
    { english: "script", chinese: "腳本", difficulty: 1 },
    { english: "executable", chinese: "可執行檔", difficulty: 1 },
    { english: "binary", chinese: "二進位檔", difficulty: 2 },
    { english: "config file", chinese: "設定檔", difficulty: 1 },
    { english: "dotfile", chinese: "隱藏設定檔", difficulty: 2 },
    { english: "crontab", chinese: "排程設定表", difficulty: 2 },
    { english: "SSH key", chinese: "SSH 金鑰", difficulty: 2 },
    { english: "mount", chinese: "掛載", difficulty: 2 },
    { english: "disk space", chinese: "磁碟空間", difficulty: 1 },
    { english: "memory usage", chinese: "記憶體使用量", difficulty: 1 },
    { english: "CPU usage", chinese: "CPU 使用率", difficulty: 1 },
    { english: "top", chinese: "系統監控指令", difficulty: 1 },
    { english: "kill", chinese: "終止程序", difficulty: 1 },
    { english: "background process", chinese: "背景程序", difficulty: 2 },
  ],
  architecture: [
    { english: "monolith", chinese: "單體架構", difficulty: 2 },
    { english: "microservices", chinese: "微服務架構", difficulty: 2 },
    { english: "event-driven", chinese: "事件驅動架構", difficulty: 2 },
    { english: "message queue", chinese: "訊息佇列", difficulty: 2 },
    { english: "pub/sub", chinese: "發布/訂閱模式", difficulty: 2 },
    { english: "broker", chinese: "訊息代理", difficulty: 2 },
    { english: "consumer", chinese: "消費者（訊息接收）", difficulty: 2 },
    { english: "producer", chinese: "生產者（訊息發送）", difficulty: 2 },
    { english: "coupling", chinese: "耦合", difficulty: 2 },
    { english: "decoupling", chinese: "解耦", difficulty: 2 },
    { english: "cohesion", chinese: "內聚力", difficulty: 3 },
    { english: "separation of concerns", chinese: "關注點分離", difficulty: 2 },
    { english: "MVC", chinese: "模型-視圖-控制器", difficulty: 1 },
    { english: "MVVM", chinese: "模型-視圖-視圖模型", difficulty: 2 },
    { english: "repository pattern", chinese: "儲存庫模式", difficulty: 2 },
    { english: "dependency injection", chinese: "依賴注入", difficulty: 2 },
    { english: "inversion of control", chinese: "控制反轉", difficulty: 3 },
    { english: "SOLID", chinese: "SOLID 設計原則", difficulty: 2 },
    { english: "DRY", chinese: "不重複原則", difficulty: 1 },
    { english: "KISS", chinese: "保持簡單原則", difficulty: 1 },
    { english: "YAGNI", chinese: "你不會需要它原則", difficulty: 2 },
    { english: "clean architecture", chinese: "整潔架構", difficulty: 2 },
    { english: "domain", chinese: "領域（業務範疇）", difficulty: 2 },
    { english: "bounded context", chinese: "界限上下文", difficulty: 3 },
    { english: "aggregate root", chinese: "聚合根", difficulty: 3 },
    { english: "entity", chinese: "實體", difficulty: 1 },
    { english: "value object", chinese: "值物件", difficulty: 2 },
    { english: "DTO", chinese: "資料傳輸物件", difficulty: 2 },
    { english: "facade", chinese: "外觀模式", difficulty: 2 },
    { english: "adapter", chinese: "適配器模式", difficulty: 2 },
    { english: "strategy pattern", chinese: "策略模式", difficulty: 2 },
    { english: "middleware pattern", chinese: "中介軟體模式", difficulty: 2 },
    { english: "plugin", chinese: "插件", difficulty: 1 },
    { english: "extension", chinese: "擴充", difficulty: 1 },
    { english: "hook", chinese: "鉤子（擴充點）", difficulty: 2 },
    { english: "event loop", chinese: "事件迴圈", difficulty: 2 },
    { english: "state machine", chinese: "狀態機", difficulty: 2 },
    { english: "saga", chinese: "Saga（分散式交易）", difficulty: 3 },
    { english: "circuit breaker", chinese: "斷路器模式", difficulty: 3 },
    { english: "load shedding", chinese: "負載脫落", difficulty: 3 },
    { english: "back pressure", chinese: "背壓", difficulty: 3 },
    { english: "idempotency", chinese: "冪等性", difficulty: 3 },
    { english: "eventual consistency", chinese: "最終一致性", difficulty: 3 },
    { english: "strong consistency", chinese: "強一致性", difficulty: 3 },
    { english: "CAP theorem", chinese: "CAP 定理", difficulty: 3 },
  ],
  performance: [
    { english: "optimization", chinese: "最佳化", difficulty: 1 },
    { english: "benchmark", chinese: "基準測試", difficulty: 2 },
    { english: "profiling", chinese: "效能分析", difficulty: 2 },
    { english: "bottleneck", chinese: "瓶頸", difficulty: 1 },
    { english: "memory leak", chinese: "記憶體洩漏", difficulty: 2 },
    { english: "garbage collection", chinese: "垃圾回收", difficulty: 2 },
    { english: "heap", chinese: "堆積記憶體", difficulty: 2 },
    { english: "stack overflow", chinese: "堆疊溢位", difficulty: 2 },
    { english: "buffer", chinese: "緩衝區", difficulty: 2 },
    { english: "caching strategy", chinese: "快取策略", difficulty: 2 },
    { english: "cache invalidation", chinese: "快取失效", difficulty: 2 },
    { english: "TTL", chinese: "存活時間", difficulty: 2 },
    { english: "response time", chinese: "回應時間", difficulty: 1 },
    { english: "load testing", chinese: "負載測試", difficulty: 2 },
    { english: "stress testing", chinese: "壓力測試", difficulty: 2 },
    { english: "concurrent users", chinese: "同時在線使用者", difficulty: 2 },
    { english: "requests per second", chinese: "每秒請求數", difficulty: 2 },
    { english: "percentile", chinese: "百分位數（P99）", difficulty: 2 },
    { english: "query optimization", chinese: "查詢最佳化", difficulty: 2 },
    { english: "indexing", chinese: "建立索引", difficulty: 1 },
    { english: "slow query", chinese: "慢查詢", difficulty: 1 },
    { english: "connection pooling", chinese: "連線池化", difficulty: 2 },
    { english: "preload", chinese: "預先載入", difficulty: 1 },
    { english: "compression", chinese: "壓縮", difficulty: 1 },
    { english: "gzip", chinese: "Gzip 壓縮", difficulty: 1 },
    { english: "minification", chinese: "程式碼最小化", difficulty: 2 },
    { english: "tree shaking", chinese: "樹搖優化（移除未用碼）", difficulty: 2 },
    { english: "code splitting", chinese: "程式碼分割", difficulty: 2 },
    { english: "debounce", chinese: "防抖動", difficulty: 2 },
    { english: "throttling", chinese: "節流控制", difficulty: 2 },
    { english: "memoization", chinese: "記憶化", difficulty: 2 },
    { english: "time complexity", chinese: "時間複雜度", difficulty: 2 },
    { english: "space complexity", chinese: "空間複雜度", difficulty: 2 },
    { english: "big O notation", chinese: "大 O 表示法", difficulty: 2 },
    { english: "scalability", chinese: "可擴展性", difficulty: 2 },
  ],
  tools: [
    { english: "IDE", chinese: "整合開發環境", difficulty: 1 },
    { english: "editor", chinese: "編輯器", difficulty: 1 },
    { english: "VS Code", chinese: "Visual Studio Code 編輯器", difficulty: 1 },
    { english: "plugin", chinese: "插件（編輯器擴充）", difficulty: 1 },
    { english: "linter", chinese: "程式碼檢查工具", difficulty: 1 },
    { english: "formatter", chinese: "程式碼格式化工具", difficulty: 1 },
    { english: "debugger", chinese: "除錯器", difficulty: 1 },
    { english: "breakpoint", chinese: "中斷點（除錯用）", difficulty: 1 },
    { english: "watch", chinese: "監看變數", difficulty: 2 },
    { english: "step over", chinese: "跳過（除錯）", difficulty: 2 },
    { english: "step into", chinese: "步入（除錯）", difficulty: 2 },
    { english: "console", chinese: "控制台", difficulty: 1 },
    { english: "REPL", chinese: "互動式直譯器", difficulty: 2 },
    { english: "npm", chinese: "Node 套件管理器", difficulty: 1 },
    { english: "yarn", chinese: "JavaScript 套件管理器", difficulty: 1 },
    { english: "gem", chinese: "Ruby 套件", difficulty: 1 },
    { english: "bundler", chinese: "Ruby 套件管理器", difficulty: 1 },
    { english: "pip", chinese: "Python 套件管理器", difficulty: 1 },
    { english: "Homebrew", chinese: "macOS 套件管理器", difficulty: 1 },
    { english: "Webpack", chinese: "模組打包工具", difficulty: 2 },
    { english: "Vite", chinese: "前端建構工具", difficulty: 2 },
    { english: "ESLint", chinese: "JavaScript 檢查工具", difficulty: 1 },
    { english: "Prettier", chinese: "程式碼格式化工具", difficulty: 1 },
    { english: "Rubocop", chinese: "Ruby 風格檢查工具", difficulty: 2 },
    { english: "Docker Compose", chinese: "多容器管理工具", difficulty: 2 },
    { english: "Postman", chinese: "API 測試工具", difficulty: 1 },
    { english: "Swagger", chinese: "API 文件工具", difficulty: 2 },
    { english: "Jira", chinese: "專案管理工具", difficulty: 1 },
    { english: "Slack", chinese: "團隊溝通工具", difficulty: 1 },
    { english: "GitHub Actions", chinese: "GitHub CI/CD 工具", difficulty: 2 },
    { english: "Redis", chinese: "記憶體資料庫", difficulty: 2 },
    { english: "Nginx", chinese: "網頁伺服器", difficulty: 2 },
    { english: "Apache", chinese: "網頁伺服器", difficulty: 2 },
    { english: "RabbitMQ", chinese: "訊息佇列服務", difficulty: 2 },
    { english: "Kafka", chinese: "事件串流平台", difficulty: 2 },
    { english: "Elasticsearch", chinese: "搜尋引擎", difficulty: 2 },
    { english: "Sentry", chinese: "錯誤追蹤服務", difficulty: 2 },
    { english: "Grafana", chinese: "監控儀表板工具", difficulty: 2 },
    { english: "Prometheus", chinese: "監控指標收集器", difficulty: 2 },
    { english: "Datadog", chinese: "雲端監控平台", difficulty: 2 },
  ],
  general_3: [
    { english: "scaffold", chinese: "鷹架（快速建立）", difficulty: 1 },
    { english: "bootstrap", chinese: "啟動初始化", difficulty: 1 },
    { english: "configuration", chinese: "設定", difficulty: 1 },
    { english: "convention over configuration", chinese: "慣例優於設定", difficulty: 2 },
    { english: "dry run", chinese: "模擬執行", difficulty: 1 },
    { english: "rollback", chinese: "回滾（還原操作）", difficulty: 1 },
    { english: "migration", chinese: "遷移（升級過程）", difficulty: 1 },
    { english: "backward compatibility", chinese: "向下相容", difficulty: 2 },
    { english: "forward compatibility", chinese: "向上相容", difficulty: 2 },
    { english: "semantic versioning", chinese: "語意化版本", difficulty: 2 },
    { english: "major version", chinese: "主版本號", difficulty: 1 },
    { english: "minor version", chinese: "次版本號", difficulty: 1 },
    { english: "patch version", chinese: "修補版本號", difficulty: 1 },
    { english: "LTS", chinese: "長期支援版本", difficulty: 2 },
    { english: "stable release", chinese: "穩定版", difficulty: 1 },
    { english: "beta", chinese: "測試版", difficulty: 1 },
    { english: "alpha", chinese: "內部測試版", difficulty: 1 },
    { english: "release candidate", chinese: "候選發布版", difficulty: 2 },
    { english: "nightly build", chinese: "每日建構版", difficulty: 2 },
    { english: "open source", chinese: "開源", difficulty: 1 },
    { english: "license", chinese: "授權條款", difficulty: 1 },
    { english: "MIT license", chinese: "MIT 授權", difficulty: 1 },
    { english: "contribution", chinese: "貢獻", difficulty: 1 },
    { english: "contributor", chinese: "貢獻者", difficulty: 1 },
    { english: "maintainer", chinese: "維護者", difficulty: 1 },
    { english: "issue", chinese: "問題回報", difficulty: 1 },
    { english: "bug report", chinese: "錯誤回報", difficulty: 1 },
    { english: "feature request", chinese: "功能請求", difficulty: 1 },
    { english: "deprecation warning", chinese: "棄用警告", difficulty: 2 },
    { english: "legacy code", chinese: "遺留程式碼", difficulty: 1 },
    { english: "tech stack", chinese: "技術堆疊", difficulty: 1 },
    { english: "full stack", chinese: "全端", difficulty: 1 },
    { english: "proof of concept", chinese: "概念驗證", difficulty: 2 },
    { english: "prototype", chinese: "原型", difficulty: 1 },
    { english: "demo", chinese: "展示", difficulty: 1 },
    { english: "documentation", chinese: "文件", difficulty: 1 },
    { english: "README", chinese: "讀我檔案", difficulty: 1 },
    { english: "wiki", chinese: "維基（知識庫）", difficulty: 1 },
    { english: "tutorial", chinese: "教學", difficulty: 1 },
    { english: "getting started", chinese: "入門指南", difficulty: 1 },
    { english: "quickstart", chinese: "快速開始", difficulty: 1 },
    { english: "FAQ", chinese: "常見問題", difficulty: 1 },
    { english: "troubleshooting", chinese: "疑難排解", difficulty: 1 },
    { english: "usage", chinese: "使用方式", difficulty: 1 },
    { english: "prerequisite", chinese: "先決條件", difficulty: 2 },
    { english: "requirements", chinese: "系統需求", difficulty: 1 },
    { english: "installation", chinese: "安裝", difficulty: 1 },
    { english: "setup", chinese: "設置", difficulty: 1 },
    { english: "teardown", chinese: "拆除（清理環境）", difficulty: 2 },
    { english: "scaffold", chinese: "快速搭建", difficulty: 1 },
  ],
  frontend_3: [
    { english: "SPA", chinese: "單頁應用程式", difficulty: 2 },
    { english: "SSR", chinese: "伺服器端渲染", difficulty: 2 },
    { english: "SSG", chinese: "靜態網站產生", difficulty: 2 },
    { english: "SEO", chinese: "搜尋引擎最佳化", difficulty: 1 },
    { english: "meta tag", chinese: "中繼標籤", difficulty: 1 },
    { english: "alt text", chinese: "替代文字", difficulty: 1 },
    { english: "aria label", chinese: "無障礙標籤", difficulty: 2 },
    { english: "semantic HTML", chinese: "語意化 HTML", difficulty: 2 },
    { english: "web component", chinese: "網頁元件", difficulty: 2 },
    { english: "shadow DOM", chinese: "影子 DOM", difficulty: 3 },
    { english: "custom element", chinese: "自訂元素", difficulty: 2 },
    { english: "slot", chinese: "插槽", difficulty: 2 },
    { english: "prop", chinese: "屬性（元件傳值）", difficulty: 1 },
    { english: "state", chinese: "狀態", difficulty: 1 },
    { english: "state management", chinese: "狀態管理", difficulty: 2 },
    { english: "store", chinese: "狀態倉庫", difficulty: 2 },
    { english: "dispatch", chinese: "派發（動作）", difficulty: 2 },
    { english: "reducer", chinese: "歸約器", difficulty: 2 },
    { english: "action", chinese: "動作（狀態管理）", difficulty: 1 },
    { english: "computed property", chinese: "計算屬性", difficulty: 2 },
    { english: "watcher", chinese: "監聽器（資料變更）", difficulty: 2 },
    { english: "lifecycle", chinese: "生命週期", difficulty: 2 },
    { english: "mounted", chinese: "已掛載", difficulty: 2 },
    { english: "unmounted", chinese: "已卸載", difficulty: 2 },
    { english: "virtual DOM", chinese: "虛擬 DOM", difficulty: 2 },
    { english: "diffing", chinese: "差異比對（渲染）", difficulty: 2 },
    { english: "reconciliation", chinese: "協調（更新 DOM）", difficulty: 3 },
    { english: "PWA", chinese: "漸進式網路應用", difficulty: 2 },
    { english: "service worker", chinese: "服務工作者", difficulty: 2 },
    { english: "web worker", chinese: "網頁工作者（背景執行）", difficulty: 2 },
    { english: "local storage", chinese: "本地儲存", difficulty: 1 },
    { english: "session storage", chinese: "會話儲存", difficulty: 1 },
    { english: "IndexedDB", chinese: "瀏覽器資料庫", difficulty: 2 },
    { english: "fetch API", chinese: "擷取 API", difficulty: 1 },
    { english: "AJAX", chinese: "非同步請求", difficulty: 1 },
    { english: "cross-browser", chinese: "跨瀏覽器相容", difficulty: 2 },
    { english: "polyfill", chinese: "墊片（相容補丁）", difficulty: 2 },
    { english: "vendor prefix", chinese: "瀏覽器前綴", difficulty: 2 },
    { english: "dark mode", chinese: "深色模式", difficulty: 1 },
    { english: "theme", chinese: "主題", difficulty: 1 },
  ],
  backend_3: [
    { english: "ORM", chinese: "物件關係映射", difficulty: 2 },
    { english: "Active Record", chinese: "Active Record 模式", difficulty: 2 },
    { english: "repository pattern", chinese: "儲存庫模式", difficulty: 2 },
    { english: "migration", chinese: "資料庫版本遷移", difficulty: 1 },
    { english: "seed data", chinese: "種子資料", difficulty: 1 },
    { english: "fixture", chinese: "固定測試資料", difficulty: 2 },
    { english: "SMTP", chinese: "簡單郵件傳輸協定", difficulty: 2 },
    { english: "email template", chinese: "郵件模板", difficulty: 1 },
    { english: "webhook handler", chinese: "Webhook 處理器", difficulty: 2 },
    { english: "callback", chinese: "回呼（模型生命週期）", difficulty: 2 },
    { english: "before action", chinese: "前置動作", difficulty: 1 },
    { english: "after action", chinese: "後置動作", difficulty: 1 },
    { english: "filter", chinese: "過濾器", difficulty: 1 },
    { english: "concern", chinese: "共用模組", difficulty: 2 },
    { english: "mixin", chinese: "混入", difficulty: 2 },
    { english: "trait", chinese: "特徵（語言特性）", difficulty: 2 },
    { english: "namespace", chinese: "命名空間", difficulty: 1 },
    { english: "versioning", chinese: "版本管理（API）", difficulty: 2 },
    { english: "content type", chinese: "內容類型", difficulty: 1 },
    { english: "multipart", chinese: "多部分（檔案上傳）", difficulty: 2 },
    { english: "file upload", chinese: "檔案上傳", difficulty: 1 },
    { english: "attachment", chinese: "附件", difficulty: 1 },
    { english: "blob storage", chinese: "二進位儲存", difficulty: 2 },
    { english: "presigned URL", chinese: "預簽名網址", difficulty: 2 },
    { english: "task scheduler", chinese: "任務排程器", difficulty: 2 },
    { english: "queue worker", chinese: "佇列工作者", difficulty: 2 },
    { english: "dead letter queue", chinese: "死信佇列", difficulty: 3 },
    { english: "health endpoint", chinese: "健康檢查端點", difficulty: 1 },
    { english: "graceful shutdown", chinese: "優雅關閉", difficulty: 2 },
    { english: "hot reload", chinese: "熱重載", difficulty: 1 },
    { english: "live reload", chinese: "即時重載", difficulty: 1 },
    { english: "connection string", chinese: "連線字串", difficulty: 1 },
    { english: "DSN", chinese: "資料來源名稱", difficulty: 2 },
    { english: "adapter", chinese: "適配器", difficulty: 2 },
    { english: "driver", chinese: "驅動程式", difficulty: 1 },
  ],
  database_3: [
    { english: "NoSQL", chinese: "非關聯式資料庫", difficulty: 1 },
    { english: "MongoDB", chinese: "文件型資料庫", difficulty: 1 },
    { english: "PostgreSQL", chinese: "開源關聯式資料庫", difficulty: 1 },
    { english: "MySQL", chinese: "關聯式資料庫", difficulty: 1 },
    { english: "SQLite", chinese: "輕量級資料庫", difficulty: 1 },
    { english: "document store", chinese: "文件儲存", difficulty: 2 },
    { english: "key-value store", chinese: "鍵值儲存", difficulty: 2 },
    { english: "collection", chinese: "集合（NoSQL）", difficulty: 1 },
    { english: "document", chinese: "文件（NoSQL）", difficulty: 1 },
    { english: "embedded document", chinese: "嵌入式文件", difficulty: 2 },
    { english: "sharding", chinese: "分片", difficulty: 3 },
    { english: "replica set", chinese: "複製集", difficulty: 2 },
    { english: "write concern", chinese: "寫入關注級別", difficulty: 3 },
    { english: "read preference", chinese: "讀取偏好", difficulty: 2 },
    { english: "full-text search", chinese: "全文搜尋", difficulty: 2 },
    { english: "materialized view", chinese: "實體化檢視", difficulty: 3 },
    { english: "window function", chinese: "視窗函數", difficulty: 3 },
    { english: "CTE", chinese: "通用資料表運算式", difficulty: 3 },
    { english: "upsert", chinese: "新增或更新", difficulty: 2 },
    { english: "bulk insert", chinese: "批量新增", difficulty: 2 },
    { english: "vacuum", chinese: "清理空間（PostgreSQL）", difficulty: 2 },
    { english: "explain", chinese: "查詢計畫分析", difficulty: 2 },
    { english: "execution plan", chinese: "執行計畫", difficulty: 2 },
    { english: "table scan", chinese: "全表掃描", difficulty: 2 },
    { english: "index scan", chinese: "索引掃描", difficulty: 2 },
    { english: "foreign key constraint", chinese: "外鍵約束", difficulty: 2 },
    { english: "cascade", chinese: "級聯（自動關聯操作）", difficulty: 2 },
    { english: "soft delete", chinese: "軟刪除", difficulty: 2 },
    { english: "hard delete", chinese: "硬刪除", difficulty: 1 },
    { english: "audit trail", chinese: "稽核軌跡", difficulty: 2 },
  ],
  security: [
    { english: "vulnerability", chinese: "漏洞", difficulty: 2 },
    { english: "exploit", chinese: "利用漏洞攻擊", difficulty: 2 },
    { english: "patch", chinese: "修補程式", difficulty: 1 },
    { english: "credentials", chinese: "憑證（帳密）", difficulty: 1 },
    { english: "permission", chinese: "權限", difficulty: 1 },
    { english: "role", chinese: "角色", difficulty: 1 },
    { english: "access control", chinese: "存取控制", difficulty: 2 },
    { english: "audit log", chinese: "稽核日誌", difficulty: 2 },
    { english: "secret key", chinese: "密鑰", difficulty: 2 },
    { english: "public key", chinese: "公鑰", difficulty: 2 },
    { english: "private key", chinese: "私鑰", difficulty: 2 },
    { english: "OAuth", chinese: "開放授權協定", difficulty: 2 },
    { english: "JWT", chinese: "JSON 網路令牌", difficulty: 2 },
    { english: "two-factor authentication", chinese: "雙重驗證", difficulty: 2 },
    { english: "brute force", chinese: "暴力破解", difficulty: 2 },
    { english: "injection", chinese: "注入攻擊", difficulty: 2 },
    { english: "SQL injection", chinese: "SQL 注入攻擊", difficulty: 2 },
    { english: "sanitize", chinese: "消毒（過濾輸入）", difficulty: 2 },
    { english: "whitelist", chinese: "白名單", difficulty: 1 },
    { english: "blacklist", chinese: "黑名單", difficulty: 1 },
    { english: "encrypt", chinese: "加密", difficulty: 1 },
    { english: "decrypt", chinese: "解密", difficulty: 1 },
    { english: "hash function", chinese: "雜湊函式", difficulty: 2 },
    { english: "salt", chinese: "鹽（加密用隨機值）", difficulty: 2 },
    { english: "secure", chinese: "安全的", difficulty: 1 },
  ],
  mobile: [
    { english: "native app", chinese: "原生應用程式", difficulty: 1 },
    { english: "hybrid app", chinese: "混合式應用程式", difficulty: 2 },
    { english: "cross-platform", chinese: "跨平台", difficulty: 1 },
    { english: "React Native", chinese: "跨平台框架（React）", difficulty: 2 },
    { english: "Flutter", chinese: "跨平台框架（Google）", difficulty: 2 },
    { english: "APK", chinese: "Android 安裝檔", difficulty: 1 },
    { english: "IPA", chinese: "iOS 安裝檔", difficulty: 1 },
    { english: "app store", chinese: "應用程式商店", difficulty: 1 },
    { english: "push notification", chinese: "推播通知", difficulty: 1 },
    { english: "deep link", chinese: "深度連結", difficulty: 2 },
    { english: "gesture", chinese: "手勢操作", difficulty: 1 },
    { english: "touch event", chinese: "觸控事件", difficulty: 1 },
    { english: "screen", chinese: "畫面", difficulty: 1 },
    { english: "navigation", chinese: "導覽", difficulty: 1 },
    { english: "splash screen", chinese: "啟動畫面", difficulty: 1 },
    { english: "offline mode", chinese: "離線模式", difficulty: 1 },
    { english: "geolocation", chinese: "地理定位", difficulty: 2 },
    { english: "biometric", chinese: "生物辨識", difficulty: 2 },
    { english: "responsive design", chinese: "響應式設計", difficulty: 1 },
    { english: "mobile-first", chinese: "行動優先", difficulty: 1 },
  ],
  data: [
    { english: "ETL", chinese: "擷取-轉換-載入", difficulty: 2 },
    { english: "data pipeline", chinese: "資料管線", difficulty: 2 },
    { english: "data warehouse", chinese: "資料倉儲", difficulty: 2 },
    { english: "data lake", chinese: "資料湖", difficulty: 2 },
    { english: "data model", chinese: "資料模型", difficulty: 1 },
    { english: "schema design", chinese: "結構設計", difficulty: 2 },
    { english: "data migration", chinese: "資料遷移", difficulty: 1 },
    { english: "data integrity", chinese: "資料完整性", difficulty: 2 },
    { english: "data validation", chinese: "資料驗證", difficulty: 1 },
    { english: "data cleansing", chinese: "資料清洗", difficulty: 2 },
    { english: "data transformation", chinese: "資料轉換", difficulty: 2 },
    { english: "batch processing", chinese: "批次處理", difficulty: 2 },
    { english: "stream processing", chinese: "串流處理", difficulty: 2 },
    { english: "real-time", chinese: "即時的", difficulty: 1 },
    { english: "near real-time", chinese: "近即時的", difficulty: 2 },
    { english: "analytics", chinese: "分析", difficulty: 1 },
    { english: "dashboard", chinese: "儀表板", difficulty: 1 },
    { english: "metric", chinese: "指標", difficulty: 1 },
    { english: "KPI", chinese: "關鍵績效指標", difficulty: 2 },
    { english: "report", chinese: "報表", difficulty: 1 },
    { english: "aggregation", chinese: "資料彙總", difficulty: 2 },
    { english: "time series", chinese: "時間序列", difficulty: 2 },
    { english: "histogram", chinese: "直方圖", difficulty: 2 },
    { english: "CSV", chinese: "逗號分隔值檔案", difficulty: 1 },
    { english: "JSON Lines", chinese: "JSON 行格式", difficulty: 2 },
    { english: "Parquet", chinese: "列式儲存格式", difficulty: 3 },
    { english: "schema evolution", chinese: "結構演進", difficulty: 3 },
    { english: "data governance", chinese: "資料治理", difficulty: 2 },
    { english: "data catalog", chinese: "資料目錄", difficulty: 2 },
    { english: "lineage", chinese: "資料血統（來源追蹤）", difficulty: 3 },
  ],
  api: [
    { english: "RESTful", chinese: "符合 REST 規範的", difficulty: 1 },
    { english: "endpoint URL", chinese: "端點網址", difficulty: 1 },
    { english: "HTTP method", chinese: "HTTP 方法", difficulty: 1 },
    { english: "GET request", chinese: "GET 請求（讀取）", difficulty: 1 },
    { english: "POST request", chinese: "POST 請求（新增）", difficulty: 1 },
    { english: "PUT request", chinese: "PUT 請求（更新）", difficulty: 1 },
    { english: "PATCH request", chinese: "PATCH 請求（部分更新）", difficulty: 1 },
    { english: "DELETE request", chinese: "DELETE 請求（刪除）", difficulty: 1 },
    { english: "request body", chinese: "請求主體", difficulty: 1 },
    { english: "response body", chinese: "回應主體", difficulty: 1 },
    { english: "query parameter", chinese: "查詢參數", difficulty: 1 },
    { english: "path parameter", chinese: "路徑參數", difficulty: 1 },
    { english: "request header", chinese: "請求標頭", difficulty: 1 },
    { english: "response header", chinese: "回應標頭", difficulty: 1 },
    { english: "content negotiation", chinese: "內容協商", difficulty: 2 },
    { english: "Accept header", chinese: "Accept 標頭", difficulty: 2 },
    { english: "Authorization header", chinese: "授權標頭", difficulty: 2 },
    { english: "Bearer token", chinese: "Bearer 令牌", difficulty: 2 },
    { english: "API key", chinese: "API 金鑰", difficulty: 1 },
    { english: "rate limit header", chinese: "速率限制標頭", difficulty: 2 },
    { english: "HTTP 200", chinese: "成功", difficulty: 1 },
    { english: "HTTP 201", chinese: "已建立", difficulty: 1 },
    { english: "HTTP 204", chinese: "無內容", difficulty: 1 },
    { english: "HTTP 400", chinese: "錯誤請求", difficulty: 1 },
    { english: "HTTP 401", chinese: "未授權", difficulty: 1 },
    { english: "HTTP 403", chinese: "禁止存取", difficulty: 1 },
    { english: "HTTP 404", chinese: "找不到", difficulty: 1 },
    { english: "HTTP 422", chinese: "無法處理的實體", difficulty: 2 },
    { english: "HTTP 429", chinese: "請求過多", difficulty: 2 },
    { english: "HTTP 500", chinese: "伺服器內部錯誤", difficulty: 1 },
    { english: "HTTP 502", chinese: "錯誤的閘道", difficulty: 2 },
    { english: "HTTP 503", chinese: "服務不可用", difficulty: 2 },
    { english: "OpenAPI", chinese: "API 描述規範", difficulty: 2 },
    { english: "schema validation", chinese: "結構驗證", difficulty: 2 },
    { english: "pagination token", chinese: "分頁令牌", difficulty: 2 },
    { english: "cursor pagination", chinese: "游標分頁", difficulty: 2 },
    { english: "offset pagination", chinese: "偏移分頁", difficulty: 2 },
    { english: "webhook callback", chinese: "Webhook 回呼", difficulty: 2 },
    { english: "API gateway", chinese: "API 閘道", difficulty: 2 },
    { english: "SDK", chinese: "軟體開發套件", difficulty: 1 },
  ],
  general_4: [
    { english: "namespace collision", chinese: "命名空間衝突", difficulty: 2 },
    { english: "naming convention", chinese: "命名慣例", difficulty: 1 },
    { english: "camelCase", chinese: "駝峰式命名", difficulty: 1 },
    { english: "snake_case", chinese: "蛇形命名", difficulty: 1 },
    { english: "PascalCase", chinese: "帕斯卡命名", difficulty: 1 },
    { english: "kebab-case", chinese: "串烤命名", difficulty: 1 },
    { english: "constant case", chinese: "常數命名（全大寫）", difficulty: 1 },
    { english: "scope", chinese: "作用域", difficulty: 1 },
    { english: "global scope", chinese: "全域作用域", difficulty: 1 },
    { english: "local scope", chinese: "區域作用域", difficulty: 1 },
    { english: "hoisting", chinese: "提升（JS 變數提升）", difficulty: 2 },
    { english: "strict mode", chinese: "嚴格模式", difficulty: 2 },
    { english: "type safety", chinese: "型別安全", difficulty: 2 },
    { english: "type inference", chinese: "型別推斷", difficulty: 2 },
    { english: "generics", chinese: "泛型", difficulty: 2 },
    { english: "interface implementation", chinese: "介面實作", difficulty: 2 },
    { english: "abstract class", chinese: "抽象類別", difficulty: 2 },
    { english: "concrete class", chinese: "具體類別", difficulty: 2 },
    { english: "static method", chinese: "靜態方法", difficulty: 1 },
    { english: "instance method", chinese: "實例方法", difficulty: 1 },
    { english: "getter", chinese: "取值器", difficulty: 1 },
    { english: "setter", chinese: "設值器", difficulty: 1 },
    { english: "constructor", chinese: "建構子", difficulty: 1 },
    { english: "destructor", chinese: "解構子", difficulty: 2 },
    { english: "prototype", chinese: "原型（物件）", difficulty: 2 },
    { english: "prototype chain", chinese: "原型鏈", difficulty: 2 },
    { english: "spread operator", chinese: "展開運算子", difficulty: 2 },
    { english: "destructuring", chinese: "解構賦值", difficulty: 2 },
    { english: "template literal", chinese: "模板字面值", difficulty: 2 },
    { english: "ternary operator", chinese: "三元運算子", difficulty: 1 },
    { english: "null coalescing", chinese: "空值合併", difficulty: 2 },
    { english: "optional chaining", chinese: "可選串連", difficulty: 2 },
    { english: "short circuit", chinese: "短路求值", difficulty: 2 },
    { english: "truthy", chinese: "真值", difficulty: 1 },
    { english: "falsy", chinese: "假值", difficulty: 1 },
    { english: "type coercion", chinese: "型別強制轉換", difficulty: 2 },
    { english: "implicit conversion", chinese: "隱式轉換", difficulty: 2 },
    { english: "explicit conversion", chinese: "顯式轉換", difficulty: 2 },
    { english: "regular expression", chinese: "正規表達式", difficulty: 2 },
    { english: "regex", chinese: "正則表達式", difficulty: 2 },
    { english: "escape character", chinese: "跳脫字元", difficulty: 2 },
    { english: "wildcard", chinese: "萬用字元", difficulty: 1 },
    { english: "glob pattern", chinese: "通配模式", difficulty: 2 },
    { english: "interpolation", chinese: "內插（字串嵌入變數）", difficulty: 2 },
    { english: "concatenation", chinese: "串接", difficulty: 1 },
    { english: "substring", chinese: "子字串", difficulty: 1 },
    { english: "trim", chinese: "去除空白", difficulty: 1 },
    { english: "split", chinese: "分割", difficulty: 1 },
    { english: "join", chinese: "合併（陣列為字串）", difficulty: 1 },
    { english: "map", chinese: "映射（陣列轉換）", difficulty: 1 },
    { english: "filter", chinese: "過濾（陣列篩選）", difficulty: 1 },
    { english: "reduce", chinese: "歸約（陣列累積）", difficulty: 2 },
    { english: "forEach", chinese: "逐一處理", difficulty: 1 },
    { english: "sort", chinese: "排序", difficulty: 1 },
    { english: "reverse", chinese: "反轉", difficulty: 1 },
    { english: "unique", chinese: "唯一的", difficulty: 1 },
    { english: "flatten", chinese: "攤平（巢狀陣列）", difficulty: 2 },
    { english: "chunk", chinese: "分塊", difficulty: 2 },
    { english: "queue", chinese: "佇列（先進先出）", difficulty: 1 },
    { english: "stack", chinese: "堆疊（後進先出）", difficulty: 1 },
    { english: "linked list", chinese: "鏈結串列", difficulty: 2 },
    { english: "tree", chinese: "樹狀結構", difficulty: 2 },
    { english: "graph", chinese: "圖形結構", difficulty: 2 },
    { english: "binary search", chinese: "二分搜尋", difficulty: 2 },
    { english: "hash table", chinese: "雜湊表", difficulty: 2 },
    { english: "set", chinese: "集合（不重複）", difficulty: 1 },
  ],
  workflow: [
    { english: "code freeze", chinese: "程式碼凍結", difficulty: 1 },
    { english: "staging environment", chinese: "預備環境", difficulty: 1 },
    { english: "production environment", chinese: "正式環境", difficulty: 1 },
    { english: "development environment", chinese: "開發環境", difficulty: 1 },
    { english: "local environment", chinese: "本地環境", difficulty: 1 },
    { english: "onboarding", chinese: "新人引導", difficulty: 1 },
    { english: "runbook", chinese: "操作手冊", difficulty: 2 },
    { english: "postmortem", chinese: "事後檢討", difficulty: 2 },
    { english: "incident", chinese: "事件（系統故障）", difficulty: 1 },
    { english: "on-call", chinese: "值班", difficulty: 1 },
    { english: "escalation", chinese: "升級處理", difficulty: 2 },
    { english: "SOP", chinese: "標準作業程序", difficulty: 1 },
    { english: "peer review", chinese: "同儕審查", difficulty: 1 },
    { english: "approval", chinese: "核准", difficulty: 1 },
    { english: "rollback plan", chinese: "回滾計畫", difficulty: 2 },
    { english: "feature flag", chinese: "功能旗標", difficulty: 2 },
    { english: "A/B testing", chinese: "A/B 測試", difficulty: 2 },
    { english: "canary release", chinese: "金絲雀發布", difficulty: 2 },
    { english: "smoke test", chinese: "冒煙測試", difficulty: 2 },
    { english: "sanity check", chinese: "健全性檢查", difficulty: 1 },
    { english: "hotfix branch", chinese: "緊急修復分支", difficulty: 1 },
    { english: "release branch", chinese: "發布分支", difficulty: 1 },
    { english: "trunk-based development", chinese: "主幹開發", difficulty: 2 },
    { english: "Git flow", chinese: "Git 分支流程", difficulty: 2 },
    { english: "squash merge", chinese: "壓縮合併", difficulty: 2 },
    { english: "rebase merge", chinese: "變基合併", difficulty: 2 },
    { english: "fast-forward merge", chinese: "快轉合併", difficulty: 2 },
    { english: "protected branch", chinese: "受保護分支", difficulty: 1 },
    { english: "branch policy", chinese: "分支策略", difficulty: 2 },
    { english: "merge conflict resolution", chinese: "合併衝突解決", difficulty: 2 },
  ],
  observability: [
    { english: "observability", chinese: "可觀測性", difficulty: 2 },
    { english: "tracing", chinese: "追蹤", difficulty: 2 },
    { english: "distributed tracing", chinese: "分散式追蹤", difficulty: 2 },
    { english: "span", chinese: "跨度（追蹤單位）", difficulty: 2 },
    { english: "trace ID", chinese: "追蹤識別碼", difficulty: 2 },
    { english: "log aggregation", chinese: "日誌彙整", difficulty: 2 },
    { english: "structured logging", chinese: "結構化日誌", difficulty: 2 },
    { english: "log level", chinese: "日誌級別", difficulty: 1 },
    { english: "INFO", chinese: "資訊級別", difficulty: 1 },
    { english: "WARN", chinese: "警告級別", difficulty: 1 },
    { english: "ERROR", chinese: "錯誤級別", difficulty: 1 },
    { english: "DEBUG", chinese: "除錯級別", difficulty: 1 },
    { english: "FATAL", chinese: "致命級別", difficulty: 1 },
    { english: "alert rule", chinese: "告警規則", difficulty: 2 },
    { english: "threshold", chinese: "閾值", difficulty: 2 },
    { english: "anomaly detection", chinese: "異常偵測", difficulty: 2 },
    { english: "SLI", chinese: "服務等級指標", difficulty: 2 },
    { english: "SLO", chinese: "服務等級目標", difficulty: 2 },
    { english: "error budget", chinese: "錯誤預算", difficulty: 2 },
    { english: "uptime percentage", chinese: "可用率百分比", difficulty: 1 },
    { english: "latency percentile", chinese: "延遲百分位", difficulty: 2 },
    { english: "request rate", chinese: "請求速率", difficulty: 1 },
    { english: "error rate", chinese: "錯誤率", difficulty: 1 },
    { english: "saturation", chinese: "飽和度", difficulty: 2 },
    { english: "golden signals", chinese: "黃金指標", difficulty: 2 },
  ],
  misc: [
    { english: "webhook payload", chinese: "Webhook 酬載", difficulty: 2 },
    { english: "idempotent request", chinese: "冪等請求", difficulty: 2 },
    { english: "retry strategy", chinese: "重試策略", difficulty: 2 },
    { english: "exponential backoff", chinese: "指數退避", difficulty: 2 },
    { english: "circuit breaker pattern", chinese: "斷路器模式", difficulty: 3 },
    { english: "health check endpoint", chinese: "健康檢查端點", difficulty: 1 },
    { english: "readiness probe", chinese: "就緒探測", difficulty: 2 },
    { english: "liveness probe", chinese: "存活探測", difficulty: 2 },
  ],
}

vocabularies.each do |category, words|
  words.each do |word|
    Vocabulary.find_or_create_by!(english: word[:english]) do |v|
      v.chinese = word[:chinese]
      v.category = category.to_s
      v.difficulty = word[:difficulty]
    end
  end
end

puts "Seeded #{Vocabulary.count} vocabularies."
