puts "Seeding vocabularies..."

vocabularies = {
  rails: [
    { english: "scaffold", chinese: "鷹架（快速產生 CRUD）", difficulty: 1 },
    { english: "migration", chinese: "遷移（資料庫版本控制）", difficulty: 1 },
    { english: "routing", chinese: "路由", difficulty: 1 },
    { english: "controller", chinese: "控制器", difficulty: 1 },
    { english: "model", chinese: "模型", difficulty: 1 },
    { english: "view", chinese: "視圖", difficulty: 1 },
    { english: "partial", chinese: "局部樣板", difficulty: 2 },
    { english: "helper", chinese: "輔助方法", difficulty: 1 },
    { english: "concern", chinese: "關注點（模組化共用邏輯）", difficulty: 2 },
    { english: "callback", chinese: "回呼", difficulty: 2 },
    { english: "validation", chinese: "驗證", difficulty: 1 },
    { english: "association", chinese: "關聯", difficulty: 2 },
    { english: "scope", chinese: "範圍查詢", difficulty: 2 },
    { english: "turbo", chinese: "渦輪（Hotwire 頁面加速）", difficulty: 2 },
    { english: "stimulus", chinese: "刺激（Hotwire JS 框架）", difficulty: 2 },
    { english: "devise", chinese: "認證套件", difficulty: 2 },
    { english: "middleware", chinese: "中介軟體", difficulty: 2 },
    { english: "asset", chinese: "靜態資源", difficulty: 1 },
    { english: "deployment", chinese: "部署", difficulty: 1 },
    { english: "mailer", chinese: "郵件寄送器", difficulty: 2 },
    { english: "serializer", chinese: "序列化器", difficulty: 2 },
    { english: "initializer", chinese: "初始化設定檔", difficulty: 2 },
    { english: "generator", chinese: "產生器", difficulty: 1 },
    { english: "rake", chinese: "任務執行工具", difficulty: 2 },
    { english: "yield", chinese: "讓渡（輸出內容區塊）", difficulty: 3 },
  ],
  general: [
    { english: "implement", chinese: "實作", difficulty: 1 },
    { english: "deprecated", chinese: "已棄用的", difficulty: 2 },
    { english: "initialize", chinese: "初始化", difficulty: 1 },
    { english: "configure", chinese: "設定", difficulty: 1 },
    { english: "parameter", chinese: "參數", difficulty: 1 },
    { english: "instance", chinese: "實例", difficulty: 2 },
    { english: "variable", chinese: "變數", difficulty: 1 },
    { english: "method", chinese: "方法", difficulty: 1 },
    { english: "function", chinese: "函式", difficulty: 1 },
    { english: "argument", chinese: "引數", difficulty: 2 },
    { english: "syntax", chinese: "語法", difficulty: 1 },
    { english: "compile", chinese: "編譯", difficulty: 2 },
    { english: "execute", chinese: "執行", difficulty: 1 },
    { english: "debug", chinese: "除錯", difficulty: 1 },
    { english: "refactor", chinese: "重構", difficulty: 2 },
    { english: "iterate", chinese: "迭代", difficulty: 2 },
    { english: "deploy", chinese: "部署", difficulty: 1 },
    { english: "repository", chinese: "儲存庫", difficulty: 1 },
    { english: "dependency", chinese: "依賴", difficulty: 2 },
    { english: "environment", chinese: "環境", difficulty: 1 },
    { english: "inheritance", chinese: "繼承", difficulty: 2 },
    { english: "polymorphism", chinese: "多型", difficulty: 3 },
    { english: "encapsulation", chinese: "封裝", difficulty: 3 },
    { english: "abstraction", chinese: "抽象化", difficulty: 3 },
    { english: "convention", chinese: "慣例", difficulty: 2 },
  ],
  database: [
    { english: "schema", chinese: "結構描述", difficulty: 2 },
    { english: "query", chinese: "查詢", difficulty: 1 },
    { english: "index", chinese: "索引", difficulty: 2 },
    { english: "transaction", chinese: "交易", difficulty: 2 },
    { english: "constraint", chinese: "約束條件", difficulty: 2 },
    { english: "normalize", chinese: "正規化", difficulty: 3 },
    { english: "aggregate", chinese: "聚合", difficulty: 2 },
    { english: "join", chinese: "聯結", difficulty: 1 },
    { english: "primary key", chinese: "主鍵", difficulty: 1 },
    { english: "foreign key", chinese: "外鍵", difficulty: 1 },
    { english: "seed", chinese: "種子資料", difficulty: 1 },
    { english: "rollback", chinese: "回滾", difficulty: 2 },
    { english: "column", chinese: "欄位", difficulty: 1 },
    { english: "table", chinese: "資料表", difficulty: 1 },
    { english: "record", chinese: "記錄", difficulty: 1 },
    { english: "relation", chinese: "關聯", difficulty: 2 },
    { english: "persistence", chinese: "持久化", difficulty: 3 },
    { english: "throughput", chinese: "吞吐量", difficulty: 3 },
    { english: "replication", chinese: "複製（資料庫同步）", difficulty: 3 },
    { english: "partition", chinese: "分區", difficulty: 3 },
    { english: "deadlock", chinese: "死鎖", difficulty: 3 },
    { english: "cursor", chinese: "游標", difficulty: 2 },
  ],
  frontend: [
    { english: "component", chinese: "元件", difficulty: 1 },
    { english: "render", chinese: "渲染", difficulty: 1 },
    { english: "responsive", chinese: "響應式的", difficulty: 1 },
    { english: "layout", chinese: "版面配置", difficulty: 1 },
    { english: "stylesheet", chinese: "樣式表", difficulty: 1 },
    { english: "viewport", chinese: "視窗", difficulty: 2 },
    { english: "accessibility", chinese: "無障礙性", difficulty: 2 },
    { english: "animation", chinese: "動畫", difficulty: 1 },
    { english: "framework", chinese: "框架", difficulty: 1 },
    { english: "DOM", chinese: "文件物件模型", difficulty: 2 },
    { english: "event", chinese: "事件", difficulty: 1 },
    { english: "listener", chinese: "監聽器", difficulty: 2 },
    { english: "selector", chinese: "選擇器", difficulty: 2 },
    { english: "template", chinese: "模板", difficulty: 1 },
    { english: "binding", chinese: "綁定", difficulty: 2 },
    { english: "reactive", chinese: "響應式的（資料驅動）", difficulty: 2 },
    { english: "hydration", chinese: "水合（伺服器渲染後啟動）", difficulty: 3 },
    { english: "bundle", chinese: "打包", difficulty: 2 },
    { english: "minify", chinese: "壓縮（程式碼）", difficulty: 2 },
    { english: "transpile", chinese: "轉譯", difficulty: 3 },
    { english: "flexbox", chinese: "彈性盒子佈局", difficulty: 2 },
    { english: "grid", chinese: "網格佈局", difficulty: 1 },
  ],
  backend: [
    { english: "endpoint", chinese: "端點", difficulty: 1 },
    { english: "authentication", chinese: "身份驗證", difficulty: 1 },
    { english: "authorization", chinese: "授權", difficulty: 2 },
    { english: "session", chinese: "會話", difficulty: 1 },
    { english: "token", chinese: "令牌", difficulty: 2 },
    { english: "cache", chinese: "快取", difficulty: 1 },
    { english: "queue", chinese: "佇列", difficulty: 2 },
    { english: "webhook", chinese: "網路鉤子", difficulty: 2 },
    { english: "API", chinese: "應用程式介面", difficulty: 1 },
    { english: "request", chinese: "請求", difficulty: 1 },
    { english: "response", chinese: "回應", difficulty: 1 },
    { english: "header", chinese: "標頭", difficulty: 2 },
    { english: "payload", chinese: "酬載（請求內容）", difficulty: 2 },
    { english: "encryption", chinese: "加密", difficulty: 2 },
    { english: "hashing", chinese: "雜湊", difficulty: 2 },
    { english: "latency", chinese: "延遲", difficulty: 2 },
    { english: "microservice", chinese: "微服務", difficulty: 2 },
    { english: "rate limiting", chinese: "速率限制", difficulty: 2 },
    { english: "idempotent", chinese: "冪等的", difficulty: 3 },
    { english: "pagination", chinese: "分頁", difficulty: 1 },
    { english: "throttle", chinese: "節流", difficulty: 3 },
    { english: "socket", chinese: "通訊端口", difficulty: 2 },
  ],
  devops: [
    { english: "container", chinese: "容器", difficulty: 1 },
    { english: "orchestration", chinese: "編排", difficulty: 3 },
    { english: "pipeline", chinese: "管線（CI/CD 流程）", difficulty: 2 },
    { english: "monitoring", chinese: "監控", difficulty: 1 },
    { english: "scaling", chinese: "擴展", difficulty: 2 },
    { english: "load balancer", chinese: "負載均衡器", difficulty: 2 },
    { english: "registry", chinese: "映像檔倉庫", difficulty: 2 },
    { english: "volume", chinese: "卷（資料儲存）", difficulty: 2 },
    { english: "cluster", chinese: "叢集", difficulty: 2 },
    { english: "namespace", chinese: "命名空間", difficulty: 2 },
    { english: "ingress", chinese: "入口（流量管理）", difficulty: 3 },
    { english: "rollout", chinese: "滾動更新", difficulty: 2 },
    { english: "artifact", chinese: "產出物", difficulty: 2 },
    { english: "provisioning", chinese: "資源配置", difficulty: 3 },
    { english: "infrastructure", chinese: "基礎設施", difficulty: 2 },
    { english: "logging", chinese: "日誌記錄", difficulty: 1 },
    { english: "alerting", chinese: "告警", difficulty: 1 },
    { english: "uptime", chinese: "正常運行時間", difficulty: 1 },
    { english: "failover", chinese: "故障轉移", difficulty: 3 },
    { english: "CI/CD", chinese: "持續整合/持續部署", difficulty: 1 },
    { english: "Docker", chinese: "容器化平台", difficulty: 1 },
    { english: "Kubernetes", chinese: "容器編排平台", difficulty: 2 },
    { english: "daemon", chinese: "守護程序", difficulty: 2 },
    { english: "cron job", chinese: "排程任務", difficulty: 2 },
    { english: "health check", chinese: "健康檢查", difficulty: 1 },
    { english: "environment variable", chinese: "環境變數", difficulty: 1 },
    { english: "image", chinese: "映像檔", difficulty: 1 },
    { english: "tag", chinese: "標籤（版本標記）", difficulty: 1 },
    { english: "service", chinese: "服務", difficulty: 1 },
    { english: "proxy", chinese: "代理伺服器", difficulty: 2 },
    { english: "reverse proxy", chinese: "反向代理", difficulty: 2 },
    { english: "downtime", chinese: "停機時間", difficulty: 1 },
    { english: "blue-green deployment", chinese: "藍綠部署", difficulty: 2 },
    { english: "canary deployment", chinese: "金絲雀部署", difficulty: 2 },
    { english: "horizontal scaling", chinese: "水平擴展", difficulty: 2 },
    { english: "vertical scaling", chinese: "垂直擴展", difficulty: 2 },
  ],
  general_2: [
    { english: "boolean", chinese: "布林值", difficulty: 1 },
    { english: "string", chinese: "字串", difficulty: 1 },
    { english: "integer", chinese: "整數", difficulty: 1 },
    { english: "float", chinese: "浮點數", difficulty: 1 },
    { english: "array", chinese: "陣列", difficulty: 1 },
    { english: "hash", chinese: "雜湊（鍵值對集合）", difficulty: 1 },
    { english: "object", chinese: "物件", difficulty: 1 },
    { english: "class", chinese: "類別", difficulty: 1 },
    { english: "module", chinese: "模組", difficulty: 1 },
    { english: "interface", chinese: "介面", difficulty: 2 },
    { english: "library", chinese: "函式庫", difficulty: 1 },
    { english: "package", chinese: "套件", difficulty: 1 },
    { english: "constant", chinese: "常數", difficulty: 1 },
    { english: "attribute", chinese: "屬性", difficulty: 1 },
    { english: "property", chinese: "屬性（物件的）", difficulty: 1 },
    { english: "return value", chinese: "回傳值", difficulty: 1 },
    { english: "exception", chinese: "例外", difficulty: 2 },
    { english: "error handling", chinese: "錯誤處理", difficulty: 1 },
    { english: "stack trace", chinese: "堆疊追蹤", difficulty: 2 },
    { english: "runtime", chinese: "執行環境", difficulty: 2 },
    { english: "loop", chinese: "迴圈", difficulty: 1 },
    { english: "condition", chinese: "條件", difficulty: 1 },
    { english: "operator", chinese: "運算子", difficulty: 1 },
    { english: "expression", chinese: "表達式", difficulty: 2 },
    { english: "statement", chinese: "陳述句", difficulty: 2 },
    { english: "block", chinese: "區塊", difficulty: 1 },
    { english: "closure", chinese: "閉包", difficulty: 2 },
    { english: "lambda", chinese: "匿名函式", difficulty: 2 },
    { english: "recursion", chinese: "遞迴", difficulty: 2 },
    { english: "algorithm", chinese: "演算法", difficulty: 1 },
    { english: "data structure", chinese: "資料結構", difficulty: 1 },
    { english: "type", chinese: "型別", difficulty: 1 },
    { english: "cast", chinese: "型別轉換", difficulty: 2 },
    { english: "parse", chinese: "解析", difficulty: 1 },
    { english: "format", chinese: "格式化", difficulty: 1 },
    { english: "encode", chinese: "編碼", difficulty: 1 },
    { english: "decode", chinese: "解碼", difficulty: 1 },
    { english: "serialize", chinese: "序列化", difficulty: 2 },
    { english: "deserialize", chinese: "反序列化", difficulty: 2 },
    { english: "immutable", chinese: "不可變的", difficulty: 2 },
    { english: "mutable", chinese: "可變的", difficulty: 2 },
    { english: "thread", chinese: "執行緒", difficulty: 2 },
    { english: "process", chinese: "程序", difficulty: 1 },
    { english: "concurrent", chinese: "並發的", difficulty: 2 },
    { english: "asynchronous", chinese: "非同步的", difficulty: 2 },
    { english: "synchronous", chinese: "同步的", difficulty: 2 },
    { english: "callback", chinese: "回呼函式", difficulty: 2 },
    { english: "promise", chinese: "承諾（非同步處理）", difficulty: 2 },
    { english: "enum", chinese: "列舉", difficulty: 2 },
    { english: "tuple", chinese: "元組", difficulty: 2 },
    { english: "literal", chinese: "字面值", difficulty: 2 },
    { english: "annotation", chinese: "註解", difficulty: 2 },
    { english: "decorator", chinese: "裝飾器", difficulty: 2 },
    { english: "pattern", chinese: "模式", difficulty: 1 },
    { english: "design pattern", chinese: "設計模式", difficulty: 2 },
    { english: "singleton", chinese: "單例模式", difficulty: 2 },
    { english: "factory", chinese: "工廠模式", difficulty: 2 },
    { english: "observer", chinese: "觀察者模式", difficulty: 2 },
    { english: "verbose", chinese: "詳細的（輸出）", difficulty: 2 },
    { english: "truncate", chinese: "截斷", difficulty: 2 },
    { english: "compatible", chinese: "相容的", difficulty: 1 },
    { english: "backward compatible", chinese: "向下相容的", difficulty: 2 },
    { english: "breaking change", chinese: "破壞性變更", difficulty: 2 },
    { english: "workaround", chinese: "替代方案", difficulty: 1 },
    { english: "boilerplate", chinese: "樣板程式碼", difficulty: 2 },
    { english: "snippet", chinese: "程式碼片段", difficulty: 1 },
    { english: "flag", chinese: "旗標（選項開關）", difficulty: 1 },
    { english: "toggle", chinese: "切換", difficulty: 1 },
    { english: "default", chinese: "預設值", difficulty: 1 },
    { english: "override", chinese: "覆寫", difficulty: 2 },
    { english: "fallback", chinese: "備援方案", difficulty: 2 },
    { english: "graceful", chinese: "優雅的（如優雅關閉）", difficulty: 2 },
  ],
  database_2: [
    { english: "migration", chinese: "資料庫遷移", difficulty: 1 },
    { english: "insert", chinese: "新增資料", difficulty: 1 },
    { english: "update", chinese: "更新資料", difficulty: 1 },
    { english: "delete", chinese: "刪除資料", difficulty: 1 },
    { english: "select", chinese: "查詢資料", difficulty: 1 },
    { english: "where clause", chinese: "條件子句", difficulty: 1 },
    { english: "order by", chinese: "排序", difficulty: 1 },
    { english: "group by", chinese: "分組", difficulty: 2 },
    { english: "having", chinese: "分組後篩選", difficulty: 2 },
    { english: "subquery", chinese: "子查詢", difficulty: 2 },
    { english: "left join", chinese: "左聯結", difficulty: 2 },
    { english: "inner join", chinese: "內聯結", difficulty: 2 },
    { english: "unique index", chinese: "唯一索引", difficulty: 2 },
    { english: "composite index", chinese: "複合索引", difficulty: 2 },
    { english: "CRUD", chinese: "新增讀取更新刪除", difficulty: 1 },
    { english: "ORM", chinese: "物件關聯映射", difficulty: 2 },
    { english: "N+1 query", chinese: "N+1 查詢問題", difficulty: 2 },
    { english: "eager loading", chinese: "預先載入", difficulty: 2 },
    { english: "lazy loading", chinese: "延遲載入", difficulty: 2 },
    { english: "connection pool", chinese: "連線池", difficulty: 2 },
    { english: "backup", chinese: "備份", difficulty: 1 },
    { english: "restore", chinese: "還原", difficulty: 1 },
    { english: "dump", chinese: "傾印（匯出資料）", difficulty: 2 },
    { english: "trigger", chinese: "觸發器", difficulty: 2 },
    { english: "stored procedure", chinese: "預存程序", difficulty: 2 },
    { english: "view", chinese: "檢視表", difficulty: 2 },
    { english: "null", chinese: "空值", difficulty: 1 },
    { english: "default value", chinese: "預設值", difficulty: 1 },
    { english: "data type", chinese: "資料型別", difficulty: 1 },
    { english: "charset", chinese: "字元集", difficulty: 2 },
  ],
  frontend_2: [
    { english: "CSS", chinese: "階層式樣式表", difficulty: 1 },
    { english: "HTML", chinese: "超文本標記語言", difficulty: 1 },
    { english: "JavaScript", chinese: "前端程式語言", difficulty: 1 },
    { english: "hover", chinese: "滑鼠懸停", difficulty: 1 },
    { english: "click event", chinese: "點擊事件", difficulty: 1 },
    { english: "submit", chinese: "提交", difficulty: 1 },
    { english: "form", chinese: "表單", difficulty: 1 },
    { english: "input", chinese: "輸入欄位", difficulty: 1 },
    { english: "button", chinese: "按鈕", difficulty: 1 },
    { english: "dropdown", chinese: "下拉選單", difficulty: 1 },
    { english: "modal", chinese: "彈出視窗", difficulty: 1 },
    { english: "tooltip", chinese: "提示框", difficulty: 1 },
    { english: "breadcrumb", chinese: "麵包屑導覽", difficulty: 2 },
    { english: "carousel", chinese: "輪播", difficulty: 2 },
    { english: "pagination", chinese: "分頁元件", difficulty: 1 },
    { english: "lazy load", chinese: "延遲載入（圖片）", difficulty: 2 },
    { english: "placeholder", chinese: "預留位置文字", difficulty: 1 },
    { english: "margin", chinese: "外邊距", difficulty: 1 },
    { english: "padding", chinese: "內邊距", difficulty: 1 },
    { english: "border", chinese: "邊框", difficulty: 1 },
    { english: "overflow", chinese: "溢出", difficulty: 2 },
    { english: "z-index", chinese: "堆疊層級", difficulty: 2 },
    { english: "opacity", chinese: "透明度", difficulty: 1 },
    { english: "transition", chinese: "過渡效果", difficulty: 2 },
    { english: "media query", chinese: "媒體查詢（RWD）", difficulty: 2 },
    { english: "breakpoint", chinese: "斷點（RWD 寬度）", difficulty: 2 },
    { english: "font", chinese: "字型", difficulty: 1 },
    { english: "icon", chinese: "圖示", difficulty: 1 },
    { english: "SVG", chinese: "可縮放向量圖形", difficulty: 2 },
    { english: "pixel", chinese: "像素", difficulty: 1 },
  ],
  backend_2: [
    { english: "REST", chinese: "表現層狀態轉移", difficulty: 2 },
    { english: "GraphQL", chinese: "圖形查詢語言", difficulty: 2 },
    { english: "JSON", chinese: "JavaScript 物件表示法", difficulty: 1 },
    { english: "XML", chinese: "可延伸標記語言", difficulty: 2 },
    { english: "CORS", chinese: "跨來源資源共享", difficulty: 2 },
    { english: "CSRF", chinese: "跨站請求偽造", difficulty: 2 },
    { english: "XSS", chinese: "跨站腳本攻擊", difficulty: 2 },
    { english: "status code", chinese: "狀態碼", difficulty: 1 },
    { english: "redirect", chinese: "重新導向", difficulty: 1 },
    { english: "cookie", chinese: "瀏覽器小型文字檔", difficulty: 1 },
    { english: "middleware", chinese: "中介軟體", difficulty: 2 },
    { english: "route", chinese: "路由", difficulty: 1 },
    { english: "controller", chinese: "控制器", difficulty: 1 },
    { english: "service object", chinese: "服務物件", difficulty: 2 },
    { english: "background job", chinese: "背景任務", difficulty: 2 },
    { english: "worker", chinese: "工作者程序", difficulty: 2 },
    { english: "cron", chinese: "排程", difficulty: 2 },
    { english: "timeout", chinese: "逾時", difficulty: 1 },
    { english: "retry", chinese: "重試", difficulty: 1 },
    { english: "rate limit", chinese: "速率限制", difficulty: 2 },
    { english: "upload", chinese: "上傳", difficulty: 1 },
    { english: "download", chinese: "下載", difficulty: 1 },
    { english: "stream", chinese: "串流", difficulty: 2 },
    { english: "batch", chinese: "批次處理", difficulty: 2 },
    { english: "log level", chinese: "日誌等級", difficulty: 2 },
    { english: "debug mode", chinese: "除錯模式", difficulty: 1 },
    { english: "production", chinese: "正式環境", difficulty: 1 },
    { english: "staging", chinese: "預備環境", difficulty: 2 },
    { english: "development", chinese: "開發環境", difficulty: 1 },
    { english: "sandbox", chinese: "沙箱環境", difficulty: 2 },
  ],
  network: [
    { english: "HTTP", chinese: "超文本傳輸協定", difficulty: 1 },
    { english: "HTTPS", chinese: "安全超文本傳輸協定", difficulty: 1 },
    { english: "TCP", chinese: "傳輸控制協定", difficulty: 2 },
    { english: "UDP", chinese: "使用者資料報協定", difficulty: 2 },
    { english: "IP address", chinese: "網際協定位址", difficulty: 1 },
    { english: "DNS", chinese: "網域名稱系統", difficulty: 1 },
    { english: "domain", chinese: "網域", difficulty: 1 },
    { english: "subdomain", chinese: "子網域", difficulty: 1 },
    { english: "port", chinese: "連接埠", difficulty: 1 },
    { english: "protocol", chinese: "協定", difficulty: 1 },
    { english: "SSL", chinese: "安全通訊協定", difficulty: 2 },
    { english: "TLS", chinese: "傳輸層安全協定", difficulty: 2 },
    { english: "certificate", chinese: "憑證", difficulty: 2 },
    { english: "firewall", chinese: "防火牆", difficulty: 1 },
    { english: "bandwidth", chinese: "頻寬", difficulty: 2 },
    { english: "CDN", chinese: "內容傳遞網路", difficulty: 2 },
    { english: "WebSocket", chinese: "網路通訊端口", difficulty: 2 },
    { english: "handshake", chinese: "交握（連線建立）", difficulty: 2 },
    { english: "ping", chinese: "偵測連線", difficulty: 1 },
    { english: "URL", chinese: "統一資源定位符", difficulty: 1 },
    { english: "URI", chinese: "統一資源識別符", difficulty: 2 },
    { english: "query string", chinese: "查詢字串", difficulty: 1 },
    { english: "path", chinese: "路徑", difficulty: 1 },
    { english: "host", chinese: "主機", difficulty: 1 },
    { english: "server", chinese: "伺服器", difficulty: 1 },
    { english: "client", chinese: "客戶端", difficulty: 1 },
    { english: "gateway", chinese: "閘道", difficulty: 2 },
    { english: "VPN", chinese: "虛擬私人網路", difficulty: 1 },
    { english: "SSH", chinese: "安全殼層協定", difficulty: 2 },
    { english: "FTP", chinese: "檔案傳輸協定", difficulty: 1 },
  ],
  testing: [
    { english: "unit test", chinese: "單元測試", difficulty: 1 },
    { english: "integration test", chinese: "整合測試", difficulty: 2 },
    { english: "system test", chinese: "系統測試", difficulty: 2 },
    { english: "end-to-end test", chinese: "端對端測試", difficulty: 2 },
    { english: "test case", chinese: "測試案例", difficulty: 1 },
    { english: "test suite", chinese: "測試套件", difficulty: 1 },
    { english: "assertion", chinese: "斷言", difficulty: 2 },
    { english: "expect", chinese: "預期", difficulty: 1 },
    { english: "mock", chinese: "模擬物件", difficulty: 2 },
    { english: "stub", chinese: "替身物件", difficulty: 2 },
    { english: "fixture", chinese: "測試固定資料", difficulty: 2 },
    { english: "factory", chinese: "測試資料工廠", difficulty: 2 },
    { english: "coverage", chinese: "測試覆蓋率", difficulty: 1 },
    { english: "regression", chinese: "回歸測試", difficulty: 2 },
    { english: "TDD", chinese: "測試驅動開發", difficulty: 2 },
    { english: "BDD", chinese: "行為驅動開發", difficulty: 2 },
    { english: "spec", chinese: "規格（測試描述）", difficulty: 1 },
    { english: "describe", chinese: "描述（測試區塊）", difficulty: 1 },
    { english: "context", chinese: "情境（測試區塊）", difficulty: 1 },
    { english: "before hook", chinese: "前置鉤子", difficulty: 2 },
    { english: "after hook", chinese: "後置鉤子", difficulty: 2 },
    { english: "pending", chinese: "待完成的測試", difficulty: 1 },
    { english: "pass", chinese: "通過", difficulty: 1 },
    { english: "fail", chinese: "失敗", difficulty: 1 },
    { english: "flaky test", chinese: "不穩定的測試", difficulty: 2 },
  ],
  git: [
    { english: "commit", chinese: "提交", difficulty: 1 },
    { english: "branch", chinese: "分支", difficulty: 1 },
    { english: "merge", chinese: "合併", difficulty: 1 },
    { english: "rebase", chinese: "變基（重新定位基準）", difficulty: 2 },
    { english: "pull request", chinese: "合併請求", difficulty: 1 },
    { english: "push", chinese: "推送", difficulty: 1 },
    { english: "pull", chinese: "拉取", difficulty: 1 },
    { english: "fetch", chinese: "擷取（遠端資料）", difficulty: 1 },
    { english: "clone", chinese: "克隆（複製儲存庫）", difficulty: 1 },
    { english: "fork", chinese: "分叉（複製他人專案）", difficulty: 1 },
    { english: "conflict", chinese: "衝突", difficulty: 1 },
    { english: "resolve", chinese: "解決（衝突）", difficulty: 1 },
    { english: "staging area", chinese: "暫存區", difficulty: 2 },
    { english: "diff", chinese: "差異比較", difficulty: 1 },
    { english: "stash", chinese: "暫存變更", difficulty: 2 },
    { english: "checkout", chinese: "切換分支", difficulty: 1 },
    { english: "reset", chinese: "重置", difficulty: 2 },
    { english: "revert", chinese: "還原提交", difficulty: 2 },
    { english: "cherry-pick", chinese: "揀選提交", difficulty: 2 },
    { english: "remote", chinese: "遠端儲存庫", difficulty: 1 },
    { english: "origin", chinese: "預設遠端名稱", difficulty: 1 },
    { english: "main branch", chinese: "主分支", difficulty: 1 },
    { english: "feature branch", chinese: "功能分支", difficulty: 1 },
    { english: "hotfix", chinese: "緊急修復", difficulty: 1 },
    { english: "release", chinese: "發布版本", difficulty: 1 },
    { english: "changelog", chinese: "變更日誌", difficulty: 1 },
    { english: "version control", chinese: "版本控制", difficulty: 1 },
    { english: "gitignore", chinese: "Git 忽略清單", difficulty: 1 },
  ],
  security: [
    { english: "vulnerability", chinese: "漏洞", difficulty: 2 },
    { english: "exploit", chinese: "利用漏洞攻擊", difficulty: 2 },
    { english: "patch", chinese: "修補程式", difficulty: 1 },
    { english: "credentials", chinese: "憑證（帳密）", difficulty: 1 },
    { english: "permission", chinese: "權限", difficulty: 1 },
    { english: "role", chinese: "角色", difficulty: 1 },
    { english: "access control", chinese: "存取控制", difficulty: 2 },
    { english: "audit log", chinese: "稽核日誌", difficulty: 2 },
    { english: "secret key", chinese: "密鑰", difficulty: 2 },
    { english: "public key", chinese: "公鑰", difficulty: 2 },
    { english: "private key", chinese: "私鑰", difficulty: 2 },
    { english: "OAuth", chinese: "開放授權協定", difficulty: 2 },
    { english: "JWT", chinese: "JSON 網路令牌", difficulty: 2 },
    { english: "two-factor authentication", chinese: "雙重驗證", difficulty: 2 },
    { english: "brute force", chinese: "暴力破解", difficulty: 2 },
    { english: "injection", chinese: "注入攻擊", difficulty: 2 },
    { english: "SQL injection", chinese: "SQL 注入攻擊", difficulty: 2 },
    { english: "sanitize", chinese: "消毒（過濾輸入）", difficulty: 2 },
    { english: "whitelist", chinese: "白名單", difficulty: 1 },
    { english: "blacklist", chinese: "黑名單", difficulty: 1 },
    { english: "encrypt", chinese: "加密", difficulty: 1 },
    { english: "decrypt", chinese: "解密", difficulty: 1 },
    { english: "hash function", chinese: "雜湊函式", difficulty: 2 },
    { english: "salt", chinese: "鹽（加密用隨機值）", difficulty: 2 },
    { english: "secure", chinese: "安全的", difficulty: 1 },
  ],
}

vocabularies.each do |category, words|
  words.each do |word|
    Vocabulary.find_or_create_by!(english: word[:english]) do |v|
      v.chinese = word[:chinese]
      v.category = category.to_s
      v.difficulty = word[:difficulty]
    end
  end
end

puts "Seeded #{Vocabulary.count} vocabularies."
