puts "Seeding vocabularies..."

vocabularies = {
  rails: [
    { english: "scaffold", chinese: "鷹架（快速產生 CRUD）", difficulty: 1 },
    { english: "migration", chinese: "遷移（資料庫版本控制）", difficulty: 1 },
    { english: "routing", chinese: "路由", difficulty: 1 },
    { english: "controller", chinese: "控制器", difficulty: 1 },
    { english: "model", chinese: "模型", difficulty: 1 },
    { english: "view", chinese: "視圖", difficulty: 1 },
    { english: "partial", chinese: "局部樣板", difficulty: 2 },
    { english: "helper", chinese: "輔助方法", difficulty: 1 },
    { english: "concern", chinese: "關注點（模組化共用邏輯）", difficulty: 2 },
    { english: "callback", chinese: "回呼", difficulty: 2 },
    { english: "validation", chinese: "驗證", difficulty: 1 },
    { english: "association", chinese: "關聯", difficulty: 2 },
    { english: "scope", chinese: "範圍查詢", difficulty: 2 },
    { english: "turbo", chinese: "渦輪（Hotwire 頁面加速）", difficulty: 2 },
    { english: "stimulus", chinese: "刺激（Hotwire JS 框架）", difficulty: 2 },
    { english: "devise", chinese: "認證套件", difficulty: 2 },
    { english: "middleware", chinese: "中介軟體", difficulty: 2 },
    { english: "asset", chinese: "靜態資源", difficulty: 1 },
    { english: "deployment", chinese: "部署", difficulty: 1 },
    { english: "mailer", chinese: "郵件寄送器", difficulty: 2 },
    { english: "serializer", chinese: "序列化器", difficulty: 2 },
    { english: "initializer", chinese: "初始化設定檔", difficulty: 2 },
    { english: "generator", chinese: "產生器", difficulty: 1 },
    { english: "rake", chinese: "任務執行工具", difficulty: 2 },
    { english: "yield", chinese: "讓渡（輸出內容區塊）", difficulty: 3 },
  ],
  general: [
    { english: "implement", chinese: "實作", difficulty: 1 },
    { english: "deprecated", chinese: "已棄用的", difficulty: 2 },
    { english: "initialize", chinese: "初始化", difficulty: 1 },
    { english: "configure", chinese: "設定", difficulty: 1 },
    { english: "parameter", chinese: "參數", difficulty: 1 },
    { english: "instance", chinese: "實例", difficulty: 2 },
    { english: "variable", chinese: "變數", difficulty: 1 },
    { english: "method", chinese: "方法", difficulty: 1 },
    { english: "function", chinese: "函式", difficulty: 1 },
    { english: "argument", chinese: "引數", difficulty: 2 },
    { english: "syntax", chinese: "語法", difficulty: 1 },
    { english: "compile", chinese: "編譯", difficulty: 2 },
    { english: "execute", chinese: "執行", difficulty: 1 },
    { english: "debug", chinese: "除錯", difficulty: 1 },
    { english: "refactor", chinese: "重構", difficulty: 2 },
    { english: "iterate", chinese: "迭代", difficulty: 2 },
    { english: "deploy", chinese: "部署", difficulty: 1 },
    { english: "repository", chinese: "儲存庫", difficulty: 1 },
    { english: "dependency", chinese: "依賴", difficulty: 2 },
    { english: "environment", chinese: "環境", difficulty: 1 },
    { english: "inheritance", chinese: "繼承", difficulty: 2 },
    { english: "polymorphism", chinese: "多型", difficulty: 3 },
    { english: "encapsulation", chinese: "封裝", difficulty: 3 },
    { english: "abstraction", chinese: "抽象化", difficulty: 3 },
    { english: "convention", chinese: "慣例", difficulty: 2 },
  ],
  database: [
    { english: "schema", chinese: "結構描述", difficulty: 2 },
    { english: "query", chinese: "查詢", difficulty: 1 },
    { english: "index", chinese: "索引", difficulty: 2 },
    { english: "transaction", chinese: "交易", difficulty: 2 },
    { english: "constraint", chinese: "約束條件", difficulty: 2 },
    { english: "normalize", chinese: "正規化", difficulty: 3 },
    { english: "aggregate", chinese: "聚合", difficulty: 2 },
    { english: "join", chinese: "聯結", difficulty: 1 },
    { english: "primary key", chinese: "主鍵", difficulty: 1 },
    { english: "foreign key", chinese: "外鍵", difficulty: 1 },
    { english: "seed", chinese: "種子資料", difficulty: 1 },
    { english: "rollback", chinese: "回滾", difficulty: 2 },
    { english: "column", chinese: "欄位", difficulty: 1 },
    { english: "table", chinese: "資料表", difficulty: 1 },
    { english: "record", chinese: "記錄", difficulty: 1 },
    { english: "relation", chinese: "關聯", difficulty: 2 },
    { english: "persistence", chinese: "持久化", difficulty: 3 },
    { english: "throughput", chinese: "吞吐量", difficulty: 3 },
    { english: "replication", chinese: "複製（資料庫同步）", difficulty: 3 },
    { english: "partition", chinese: "分區", difficulty: 3 },
    { english: "deadlock", chinese: "死鎖", difficulty: 3 },
    { english: "cursor", chinese: "游標", difficulty: 2 },
  ],
  frontend: [
    { english: "component", chinese: "元件", difficulty: 1 },
    { english: "render", chinese: "渲染", difficulty: 1 },
    { english: "responsive", chinese: "響應式的", difficulty: 1 },
    { english: "layout", chinese: "版面配置", difficulty: 1 },
    { english: "stylesheet", chinese: "樣式表", difficulty: 1 },
    { english: "viewport", chinese: "視窗", difficulty: 2 },
    { english: "accessibility", chinese: "無障礙性", difficulty: 2 },
    { english: "animation", chinese: "動畫", difficulty: 1 },
    { english: "framework", chinese: "框架", difficulty: 1 },
    { english: "DOM", chinese: "文件物件模型", difficulty: 2 },
    { english: "event", chinese: "事件", difficulty: 1 },
    { english: "listener", chinese: "監聽器", difficulty: 2 },
    { english: "selector", chinese: "選擇器", difficulty: 2 },
    { english: "template", chinese: "模板", difficulty: 1 },
    { english: "binding", chinese: "綁定", difficulty: 2 },
    { english: "reactive", chinese: "響應式的（資料驅動）", difficulty: 2 },
    { english: "hydration", chinese: "水合（伺服器渲染後啟動）", difficulty: 3 },
    { english: "bundle", chinese: "打包", difficulty: 2 },
    { english: "minify", chinese: "壓縮（程式碼）", difficulty: 2 },
    { english: "transpile", chinese: "轉譯", difficulty: 3 },
    { english: "flexbox", chinese: "彈性盒子佈局", difficulty: 2 },
    { english: "grid", chinese: "網格佈局", difficulty: 1 },
  ],
  backend: [
    { english: "endpoint", chinese: "端點", difficulty: 1 },
    { english: "authentication", chinese: "身份驗證", difficulty: 1 },
    { english: "authorization", chinese: "授權", difficulty: 2 },
    { english: "session", chinese: "會話", difficulty: 1 },
    { english: "token", chinese: "令牌", difficulty: 2 },
    { english: "cache", chinese: "快取", difficulty: 1 },
    { english: "queue", chinese: "佇列", difficulty: 2 },
    { english: "webhook", chinese: "網路鉤子", difficulty: 2 },
    { english: "API", chinese: "應用程式介面", difficulty: 1 },
    { english: "request", chinese: "請求", difficulty: 1 },
    { english: "response", chinese: "回應", difficulty: 1 },
    { english: "header", chinese: "標頭", difficulty: 2 },
    { english: "payload", chinese: "酬載（請求內容）", difficulty: 2 },
    { english: "encryption", chinese: "加密", difficulty: 2 },
    { english: "hashing", chinese: "雜湊", difficulty: 2 },
    { english: "latency", chinese: "延遲", difficulty: 2 },
    { english: "microservice", chinese: "微服務", difficulty: 2 },
    { english: "rate limiting", chinese: "速率限制", difficulty: 2 },
    { english: "idempotent", chinese: "冪等的", difficulty: 3 },
    { english: "pagination", chinese: "分頁", difficulty: 1 },
    { english: "throttle", chinese: "節流", difficulty: 3 },
    { english: "socket", chinese: "通訊端口", difficulty: 2 },
  ],
  devops: [
    { english: "container", chinese: "容器", difficulty: 1 },
    { english: "orchestration", chinese: "編排", difficulty: 3 },
    { english: "pipeline", chinese: "管線（CI/CD 流程）", difficulty: 2 },
    { english: "monitoring", chinese: "監控", difficulty: 1 },
    { english: "scaling", chinese: "擴展", difficulty: 2 },
    { english: "load balancer", chinese: "負載均衡器", difficulty: 2 },
    { english: "registry", chinese: "映像檔倉庫", difficulty: 2 },
    { english: "volume", chinese: "卷（資料儲存）", difficulty: 2 },
    { english: "cluster", chinese: "叢集", difficulty: 2 },
    { english: "namespace", chinese: "命名空間", difficulty: 2 },
    { english: "ingress", chinese: "入口（流量管理）", difficulty: 3 },
    { english: "rollout", chinese: "滾動更新", difficulty: 2 },
    { english: "artifact", chinese: "產出物", difficulty: 2 },
    { english: "provisioning", chinese: "資源配置", difficulty: 3 },
    { english: "infrastructure", chinese: "基礎設施", difficulty: 2 },
    { english: "logging", chinese: "日誌記錄", difficulty: 1 },
    { english: "alerting", chinese: "告警", difficulty: 1 },
    { english: "uptime", chinese: "正常運行時間", difficulty: 1 },
    { english: "failover", chinese: "故障轉移", difficulty: 3 },
    { english: "CI/CD", chinese: "持續整合/持續部署", difficulty: 1 },
    { english: "Docker", chinese: "容器化平台", difficulty: 1 },
    { english: "Kubernetes", chinese: "容器編排平台", difficulty: 2 },
  ],
}

vocabularies.each do |category, words|
  words.each do |word|
    Vocabulary.find_or_create_by!(english: word[:english]) do |v|
      v.chinese = word[:chinese]
      v.category = category.to_s
      v.difficulty = word[:difficulty]
    end
  end
end

puts "Seeded #{Vocabulary.count} vocabularies."
